#!/bin/bash
# generate-dataflow-diagram.sh — Generate a Mermaid data flow diagram for a Skill
# Usage: bash generate-dataflow-diagram.sh <skill-path> [--output=<path>]
#
# Reads SKILL.md frontmatter and workflow steps, then produces a Mermaid
# data-flow diagram that visualises how data moves through the Skill.

set -euo pipefail

SKILL_PATH="${1:?Usage: bash generate-dataflow-diagram.sh <skill-path> [--output=<path>]}"
OUTPUT_FLAG="${2:-}"

if [[ "$OUTPUT_FLAG" == --output=* ]]; then
  OUTPUT_FILE="${OUTPUT_FLAG#--output=}"
else
  OUTPUT_FILE=""
fi

SKILL_MD="$SKILL_PATH/SKILL.md"

if [[ ! -f "$SKILL_MD" ]]; then
  echo "Error: $SKILL_MD not found" >&2
  exit 1
fi

# --- Extract frontmatter fields ---
extract_fm() {
  local field="$1"
  awk -v f="$field" '
    /^---/{c++;next}
    c==1 && index($0, f":")==1{
      sub(f":[[:space:]]*", "")
      print; found=1; next
    }
    c==1 && found && /^[[:space:]]/ && !/^[a-z]/{
      gsub(/^[[:space:]]+/, "")
      print; next
    }
    c==1 && found{exit}
  ' "$SKILL_MD" | tr -d '\n' | sed 's/^[[:space:]]*//;s/[[:space:]]*$//'
}

SKILL_NAME=$(extract_fm "name" || echo "unknown-skill")
SKILL_VERSION=$(extract_fm "version" || echo "0.0.0")

# --- Extract workflow steps from SKILL.md ---
# Look for ### Step N: or ### N. patterns
STEPS=()
while IFS= read -r line; do
  step=$(printf '%s' "$line" | sed -E 's/^###[[:space:]]+(Step[[:space:]]+)?[0-9]+[.:]?[[:space:]]*//;s/^##[[:space:]]+[0-9]+[.:][[:space:]]*//')
  if [[ -n "$step" ]]; then
    STEPS+=("$step")
  fi
done < <(grep -E '^###[[:space:]]+(Step[[:space:]]+)?[0-9]+|^##[[:space:]]+[0-9]+\.' "$SKILL_MD" 2>/dev/null || true)

# --- Extract CLI commands (Service Operation pairs) ---
CLI_OPS=()
while IFS= read -r cmd; do
  if [[ -n "$cmd" ]]; then
    CLI_OPS+=("$cmd")
  fi
done < <(grep -oE 'hcloud [A-Z]+ [A-Za-z]+' "$SKILL_MD" 2>/dev/null | sort -u | head -10 || true)

# --- Build Mermaid diagram ---
{
  echo "# Data Flow Diagram — ${SKILL_NAME}"
  echo ""
  echo "> Auto-generated by \`scripts/generate-dataflow-diagram.sh\` | Version: ${SKILL_VERSION}"
  echo ""
  echo "## Workflow Data Flow"
  echo ""
  echo '```mermaid'
  echo "flowchart TD"

  # Input node
  echo "  INPUT([\"User Request / Trigger\"])"

  # Step nodes
  if [[ ${#STEPS[@]} -eq 0 ]]; then
    STEPS=("Requirements Analysis" "Execute Workflow" "Return Results")
  fi

  for i in "${!STEPS[@]}"; do
    idx=$((i + 1))
    # Sanitize step name for Mermaid node ID
    node_id="STEP${idx}"
    echo "  ${node_id}[\"${STEPS[$i]}\"]"
  done

  # Output node
  echo "  OUTPUT([\"Skill Output / Result\"])"

  # CLI operation subgraph (if any)
  if [[ ${#CLI_OPS[@]} -gt 0 ]]; then
    echo "  subgraph CLI_OPS[\"CLI Operations\"]"
    for i in "${!CLI_OPS[@]}"; do
      op_id="CLI_OP$((i + 1))"
      echo "    ${op_id}[\"${CLI_OPS[$i]}\"]"
    done
    echo "  end"
  fi

  # Data store nodes
  echo "  subgraph DATA[\"Data Sources\"]"
  echo "    ENV[[\"Environment Variables\nAK/SK, Region\"]]"
  echo "    REFS[\"references/\nDocs & Policies\"]"
  echo "    SCRIPTS[\"scripts/\nAutomation\"]"
  echo "  end"

  # Edges: input → steps → output
  echo "  INPUT --> STEP1"
  for i in "${!STEPS[@]}"; do
    idx=$((i + 1))
    next=$((idx + 1))
    if [[ $next -le ${#STEPS[@]} ]]; then
      echo "  STEP${idx} --> STEP${next}"
    fi
  done
  echo "  STEP${#STEPS[@]} --> OUTPUT"

  # Edges: data stores feed into steps
  echo "  ENV -.-> STEP1"
  if [[ ${#STEPS[@]} -ge 2 ]]; then
    echo "  REFS -.-> STEP2"
  fi

  # Edges: CLI ops connected to relevant steps
  if [[ ${#CLI_OPS[@]} -gt 0 ]]; then
    for i in "${!CLI_OPS[@]}"; do
      op_id="CLI_OP$((i + 1))"
      target_step=$(( (i % ${#STEPS[@]}) + 1 ))
      if [[ $target_step -gt 1 ]]; then
        echo "  ${op_id} -.-> STEP${target_step}"
      fi
    done
    echo "  STEP1 --> CLI_OPS"
  fi

  echo '```'
  echo ""
  echo "## Diagram Legend"
  echo ""
  echo "| Symbol | Meaning |"
  echo "|--------|---------|"
  echo '| `([ ])` | Start / End (rounded rectangle) |'
  echo '| `[ ]` | Process step (rectangle) |'
  echo '| `[[ ]]` | Data store (double rectangle) |'
  echo '| `-->` | Primary data flow |'
  echo '| `-.->` | Secondary / reference data flow |'
  echo ""
  echo "## Data Flow Description"
  echo ""
  echo "| Step | Input | Process | Output |"
  echo "|------|-------|---------|--------|"

  for i in "${!STEPS[@]}"; do
    idx=$((i + 1))
    if [[ $idx -eq 1 ]]; then
      echo "| ${idx}. ${STEPS[$i]} | User request + env config | Analyse and validate input | Structured requirements |"
    elif [[ $idx -eq ${#STEPS[@]} ]]; then
      echo "| ${idx}. ${STEPS[$i]} | Processed results | Format and validate output | Final skill output |"
    else
      echo "| ${idx}. ${STEPS[$i]} | Previous step output + references | Execute workflow step | Intermediate result |"
    fi
  done

} > /tmp/dataflow_output.md

# --- Output ---
if [[ -n "$OUTPUT_FILE" ]]; then
  cp /tmp/dataflow_output.md "$OUTPUT_FILE"
  echo "Data flow diagram written to: $OUTPUT_FILE"
else
  cat /tmp/dataflow_output.md
fi

rm -f /tmp/dataflow_output.md
