# -*- coding: utf-8 -*-
"""
ClickHouse 24.8 SQL Keyword Definitions

Source: ClickHouse 24.8 kernel src/Parsers/CommonParsers.h
  - APPLY_FOR_PARSER_KEYWORDS            (main keyword list)
  - APPLY_FOR_PARSER_KEYWORDS_WITH_UNDERSCORES (keywords with underscores)

ClickHouse keywords are case-insensitive and require word boundaries.
Compound keywords (e.g. "ORDER BY") allow whitespace/comments between parts.

The KEYWORDS tuple below is the authoritative, complete list extracted
directly from the kernel source (571 unique keyword strings, preserving
original case as written in the source). is_keyword() does a
case-insensitive lookup against this set.

Category subsets (DML/DDL/DCL/...) are provided for reporting and rule
targeting only — a keyword may appear in more than one category. They are
NOT the source of truth; KEYWORDS is.
"""

from enum import Enum


class KeywordCategory(Enum):
    """Keyword category for reporting."""
    DML = "DML"
    DDL = "DDL"
    DCL = "DCL"
    TCL = "TCL"
    UTILITY = "Utility"
    ACCESS = "Access Control"
    SELECT_CLAUSE = "SELECT Clause"
    JOIN = "JOIN"
    OPERATOR = "Operator/Predicate"
    DATA_TYPE = "Data Type"
    TIME_UNIT = "Time Unit"
    DATE_TOKEN = "Date Format Token"
    DICTIONARY = "Dictionary"
    PARTITION = "Partition/Part"
    ALTER_ACTION = "ALTER Action"
    SETTING = "Setting"
    SHOW = "SHOW"
    MISC = "Miscellaneous"


# =============================================================================
# Authoritative keyword list (extracted from CommonParsers.h, 571 entries)
# Case preserved as in source. Matched case-insensitively.
# =============================================================================
KEYWORDS = (
    "ADD", "ADD COLUMN", "ADD CONSTRAINT", "ADD INDEX", "ADD PROJECTION",
    "ADD STATISTICS", "ADMIN OPTION FOR", "AFTER", "ALGORITHM", "ALIAS", "ALL",
    "ALLOWED_LATENESS", "ALTER", "ALTER COLUMN", "ALTER DATABASE",
    "ALTER LIVE VIEW", "ALTER POLICY", "ALTER PROFILE", "ALTER QUOTA",
    "ALTER ROLE", "ALTER ROW POLICY", "ALTER SETTINGS PROFILE",
    "ALTER TABLE", "ALTER TEMPORARY TABLE", "ALTER TENANT", "ALTER USER",
    "AND", "AND STDOUT", "ANTI", "ANY", "APPEND", "APPLY",
    "APPLY DELETED MASK", "ARRAY JOIN", "AS", "ASC", "ASCENDING", "ASOF",
    "ASSUME", "AST", "ASYNC", "ATTACH", "ATTACH PART", "ATTACH PARTITION",
    "ATTACH POLICY", "ATTACH PROFILE", "ATTACH QUOTA", "ATTACH ROLE",
    "ATTACH ROW POLICY", "ATTACH SETTINGS PROFILE", "ATTACH TENANT",
    "ATTACH USER", "AUTO_INCREMENT", "AZURE", "BACKUP", "BCRYPT_HASH",
    "BCRYPT_PASSWORD", "BEGIN TRANSACTION", "BETWEEN", "BIDIRECTIONAL",
    "BOTH", "BY", "CASCADE", "CASE", "CAST", "CHANGE", "CHANGEABLE_IN_READONLY",
    "CHANGED", "CHAR", "CHAR VARYING", "CHARACTER", "CHARACTER LARGE OBJECT",
    "CHARACTER VARYING", "CHECK", "CHECK ALL TABLES", "CHECK TABLE",
    "CHECK TRANSACTION", "CLEANUP", "CLEAR COLUMN", "CLEAR INDEX",
    "CLEAR PROJECTION", "CLEAR STATISTICS", "CLUSTER", "CLUSTERS", "CN",
    "CODEC", "COLLATE", "COLUMN", "COLUMNS", "COMMENT", "COMMENT COLUMN",
    "COMMIT", "COMPRESSION", "CONST", "CONSTRAINT", "CREATE", "CREATE POLICY",
    "CREATE PROFILE", "CREATE QUOTA", "CREATE ROLE", "CREATE ROW POLICY",
    "CREATE SETTINGS PROFILE", "CREATE TABLE", "CREATE TEMPORARY TABLE",
    "CREATE TENANT", "CREATE USER", "CROSS", "CUBE", "CURRENT GRANTS",
    "CURRENT QUOTA", "CURRENT ROLES", "CURRENT ROW", "CURRENT TRANSACTION",
    "CURRENTUSER", "CURRENT_USER", "D", "DATA", "DATA INNER UUID", "DATABASE",
    "DATABASES", "DATE", "DAY", "DAYS", "DD", "DDLTASK", "DEDUPLICATE",
    "DEFAULT", "DEFAULT DATABASE", "DEFAULT ROLE", "DEFINER", "DELETE",
    "DEPENDS ON", "DESC", "DESCENDING", "DESCRIBE", "DETACH", "DETACH PART",
    "DETACH PARTITION", "DICTIONARIES", "DICTIONARY", "DISK", "DISTINCT",
    "DISTINCT ON", "DIV", "DOUBLE_SHA1_HASH", "DOUBLE_SHA1_PASSWORD", "DROP",
    "DROP COLUMN", "DROP CONSTRAINT", "DROP DEFAULT", "DROP DETACHED PART",
    "DROP DETACHED PARTITION", "DROP INDEX", "DROP PART", "DROP PARTITION",
    "DROP PROJECTION", "DROP STATISTICS", "DROP TABLE", "DROP TEMPORARY TABLE",
    "ELSE", "EMPTY", "EMPTY AS", "ENABLED ROLES", "END", "ENFORCED", "ENGINE",
    "EPHEMERAL", "EPHEMERAL SEQUENTIAL", "ESTIMATE", "EVENT", "EVENTS",
    "EVERY", "EXCEPT", "EXCEPT DATABASE", "EXCEPT DATABASES", "EXCEPT TABLE",
    "EXCEPT TABLES", "EXCHANGE DICTIONARIES", "EXCHANGE TABLES", "EXISTS",
    "EXPLAIN", "EXPRESSION", "EXTENDED", "EXTERNAL DDL FROM", "FALSE", "FETCH",
    "FETCH PART", "FETCH PARTITION", "FIELDS", "FILE", "FILESYSTEM CACHE",
    "FILESYSTEM CACHES", "FILTER", "FINAL", "FIRST", "FOLLOWING", "FOR",
    "FOREIGN", "FOREIGN KEY", "FORGET PARTITION", "FORMAT", "FREEZE", "FROM",
    "FROM INFILE", "FROM SHARD", "FULL", "FULLTEXT", "FUNCTION", "GLOBAL",
    "GLOBAL IN", "GLOBAL NOT IN", "GRANT", "GRANT OPTION FOR", "GRANTEES",
    "GRANULARITY", "GROUP BY", "GROUPING SETS", "GROUPS", "H", "HASH",
    "HAVING", "HDFS", "HH", "HIERARCHICAL", "HOST", "HOUR", "HOURS", "HTTP",
    "ID", "IDENTIFIED", "IF EMPTY", "IF EXISTS", "IF NOT EXISTS",
    "IGNORE NULLS", "ILIKE", "IN", "IN PARTITION", "INDEX", "INDEXES",
    "INDICES", "INHERIT", "INJECTIVE", "INNER", "INSERT INTO",
    "INTERPOLATE", "INTERSECT", "INTERVAL", "INTO OUTFILE", "INVISIBLE",
    "INVOKER", "IP", "IS NOT DISTINCT FROM", "IS NOT NULL", "IS NULL",
    "IS_OBJECT_ID", "JOIN", "JWT", "KERBEROS", "KEY", "KEY BY", "KEYED BY",
    "KEYS", "KILL", "KIND", "LARGE OBJECT", "LAST", "LAYOUT", "LDAP",
    "LEADING", "LEFT", "LEFT ARRAY JOIN", "LESS THAN", "LEVEL", "LIFETIME",
    "LIGHTWEIGHT", "LIKE", "LIMIT", "LINEAR", "LIST", "LIVE", "LOCAL", "M",
    "MATCH", "MATERIALIZE", "MATERIALIZE COLUMN", "MATERIALIZE INDEX",
    "MATERIALIZE PROJECTION", "MATERIALIZE STATISTICS", "MATERIALIZE TTL",
    "MATERIALIZED", "MAX", "MCS", "MEMORY", "MERGES", "METRICS",
    "METRICS INNER UUID", "MI", "MICROSECOND", "MICROSECONDS", "MILLISECOND",
    "MILLISECONDS", "MIN", "MINUTE", "MINUTES", "MM", "MOD", "MODIFY",
    "MODIFY COLUMN", "MODIFY COMMENT", "MODIFY DEFINER", "MODIFY ORDER BY",
    "MODIFY QUERY", "MODIFY REFRESH", "MODIFY SAMPLE BY", "MODIFY SETTING",
    "MODIFY SQL SECURITY", "MODIFY STATISTICS", "MODIFY TTL", "MONTH",
    "MONTHS", "MOVE", "MOVE PART", "MOVE PARTITION", "MS", "MUTATION", "N",
    "NAME", "NAMED COLLECTION", "NANOSECOND", "NANOSECONDS", "NEXT",
    "NO ACTION", "NO DELAY", "NO LIMITS", "NONE", "NOT", "NOT BETWEEN",
    "NOT IDENTIFIED", "NOT ILIKE", "NOT IN", "NOT KEYED", "NOT LIKE",
    "NOT OVERRIDABLE", "NO_PASSWORD", "NS", "NULL", "NULLS", "OFFSET", "ON",
    "ON DELETE", "ON UPDATE", "ON VOLUME", "ONLY", "OPTIMIZE TABLE", "OR",
    "OR REPLACE", "ORDER BY", "OUTER", "OVER", "OVERRIDABLE", "PART",
    "PARTIAL", "PARTITION", "PARTITION BY", "PARTITIONS", "PART_MOVE_TO_SHARD",
    "PASTE", "PBKDF2_HASH", "PBKDF2_PASSWORD", "PERIODIC REFRESH",
    "PERMANENTLY", "PERMISSIVE", "PERSISTENT", "PERSISTENT SEQUENTIAL",
    "PIPELINE", "PLAINTEXT_PASSWORD", "PLAN", "POPULATE", "PRECEDING",
    "PRECISION", "PREFIX", "PREWHERE", "PRIMARY", "PRIMARY KEY", "PROFILE",
    "PROJECTION", "Protobuf", "PULL", "Q", "QQ", "QUALIFY", "QUARTER",
    "QUARTERS", "QUERY", "QUERY TREE", "QUOTA", "RANDOMIZE FOR",
    "RANDOMIZED", "RANGE", "READONLY", "REALM", "RECOMPRESS", "RECURSIVE",
    "REFERENCES", "REFRESH", "REGEXP", "REMOVE", "REMOVE SAMPLE BY",
    "REMOVE TTL", "RENAME", "RENAME COLUMN", "RENAME DATABASE",
    "RENAME DICTIONARY", "RENAME TABLE", "RENAME TO", "REPLACE",
    "REPLACE PARTITION", "RESET SETTING", "RESPECT NULLS", "RESTORE",
    "RESTRICT", "RESTRICTIVE", "RESUME", "REVOKE", "RIGHT", "ROLLBACK",
    "ROLLUP", "ROW", "ROWS", "S", "S3", "SALT", "SAMPLE", "SAMPLE BY", "SAN",
    "SCHEME", "SECOND", "SECONDS", "SELECT", "SEMI", "SERVER", "SET",
    "SET DEFAULT", "SET DEFAULT ROLE", "SET FAKE TIME", "SET NULL",
    "SET ROLE", "SET ROLE DEFAULT", "SET TRANSACTION SNAPSHOT", "SETTINGS",
    "SHA256_HASH", "SHA256_PASSWORD", "SHOW", "SHOW ACCESS", "SHOW CREATE",
    "SHOW ENGINES", "SHOW FUNCTIONS", "SHOW GRANTS", "SHOW PRIVILEGES",
    "SHOW PROCESSLIST", "SHOW SETTING", "SIGNED", "SIMPLE", "SKIP", "SOURCE",
    "SPATIAL", "SQL SECURITY", "SQL_TSI_DAY", "SQL_TSI_HOUR",
    "SQL_TSI_MICROSECOND", "SQL_TSI_MILLISECOND", "SQL_TSI_MINUTE",
    "SQL_TSI_MONTH", "SQL_TSI_NANOSECOND", "SQL_TSI_QUARTER",
    "SQL_TSI_SECOND", "SQL_TSI_WEEK", "SQL_TSI_YEAR", "SS", "SSH_KEY",
    "SSL_CERTIFICATE", "START TRANSACTION", "STATISTICS", "STEP", "STORAGE",
    "STRICT", "STRICTLY_ASCENDING", "SUBPARTITION", "SUBPARTITION BY",
    "SUBPARTITIONS", "SUSPEND", "SYNC", "SYNTAX", "SYSTEM", "TABLE",
    "TABLE OVERRIDE", "TABLES", "TAG", "TAGS", "TAGS INNER UUID", "TEMPORARY",
    "TEMPORARY TABLE", "TENANT", "TENANTS", "TEST", "THEN", "TIMESTAMP",
    "TO", "TO DISK", "TO INNER UUID", "TO SHARD", "TO TABLE", "TO VOLUME",
    "TOP", "TOTALS", "TRACKING ONLY", "TRAILING", "TRANSACTION", "TRIGGER",
    "TRUE", "TRUNCATE", "TTL", "TYPE", "TYPEOF", "UNBOUNDED", "UNDROP",
    "UNDROP PART", "UNDROP PARTITION", "UNFREEZE", "UNION", "UNIQUE",
    "UNSET FAKE TIME", "UNSIGNED", "UPDATE", "UPSERT INTO", "URL", "USE",
    "USING", "UUID", "VALID UNTIL", "VALUES", "VARYING", "VIEW", "VISIBLE",
    "WATCH", "WATERMARK", "WEEK", "WEEKS", "WHEN", "WHERE", "WINDOW", "WITH",
    "WITH ADMIN OPTION", "WITH CHECK", "WITH FILL", "WITH GRANT OPTION",
    "WITH NAME", "WITH REPLACE OPTION", "WITH TIES", "WITH_ITEMINDEX", "WK",
    "WRITABLE", "WW", "YEAR", "YEARS", "YY", "YYYY", "ZKPATH", "bagexpansion",
    "base_backup", "cluster_host_ids",
)

# Master set (original case) + uppercase index for case-insensitive lookup.
ALL_KEYWORDS = set(KEYWORDS)
_KEYWORDS_UPPER = {k.upper() for k in KEYWORDS}


# =============================================================================
# Category subsets (for reporting/rule targeting; non-authoritative)
# =============================================================================
DML_KEYWORDS = {
    "SELECT", "INSERT INTO", "UPSERT INTO", "DELETE", "UPDATE", "VALUES",
    "OPTIMIZE TABLE", "TRUNCATE", "FROM INFILE", "INTO OUTFILE", "AND STDOUT",
    "DEDUPLICATE", "FINAL",
}

DDL_KEYWORDS = {
    "CREATE", "CREATE TABLE", "CREATE TEMPORARY TABLE", "ALTER",
    "ALTER TABLE", "ALTER TEMPORARY TABLE", "ALTER DATABASE",
    "ALTER LIVE VIEW", "DROP", "DROP TABLE", "DROP TEMPORARY TABLE",
    "RENAME", "RENAME TABLE", "RENAME DATABASE", "RENAME DICTIONARY",
    "RENAME TO", "RENAME COLUMN", "ATTACH", "DETACH", "ATTACH PART",
    "ATTACH PARTITION", "DETACH PART", "DETACH PARTITION", "UNDROP",
    "UNDROP PART", "UNDROP PARTITION", "EXCHANGE TABLES",
    "EXCHANGE DICTIONARIES", "CHECK", "CHECK TABLE", "CHECK ALL TABLES",
    "CHECK TRANSACTION", "DESCRIBE", "USE", "TRUNCATE", "EXTERNAL DDL FROM",
    "TABLE OVERRIDE", "TABLE", "TABLES", "DATABASE", "DATABASES",
    "MATERIALIZED", "VIEW", "LIVE", "FUNCTION", "INDEX", "INDEXES",
    "INDICES", "TRIGGER", "CONSTRAINT", "CONST", "COMMENT",
    "COMMENT COLUMN", "UNIQUE", "PRIMARY", "PRIMARY KEY", "FOREIGN",
    "FOREIGN KEY", "ENGINE", "TTL", "TYPE", "KIND", "DEFINER", "INVOKER",
    "SQL SECURITY", "OR REPLACE", "IF EXISTS", "IF NOT EXISTS", "IF EMPTY",
    "TEMPORARY", "TEMPORARY TABLE", "POPULATE", "AS", "WITH", "SETTINGS",
    "ORDER BY", "PARTITION BY", "SAMPLE BY", "CODEC", "COMPRESSION",
    "STATISTICS", "GRANULARITY", "PROJECTION", "SALT", "STEP", "DEPENDS ON",
    "NAMED COLLECTION", "DATA INNER UUID", "TO INNER UUID",
    "METRICS INNER UUID", "TAGS INNER UUID", "TABLE OVERRIDE", "ALGORITHM",
    "CHANGE", "CHANGED",
}

DCL_KEYWORDS = {
    "GRANT", "REVOKE", "GRANT OPTION FOR", "ADMIN OPTION FOR",
    "WITH GRANT OPTION", "WITH ADMIN OPTION", "GRANTEES",
    "CREATE USER", "CREATE ROLE", "CREATE POLICY", "CREATE PROFILE",
    "CREATE QUOTA", "CREATE ROW POLICY", "CREATE SETTINGS PROFILE",
    "ALTER USER", "ALTER ROLE", "ALTER POLICY", "ALTER PROFILE",
    "ALTER QUOTA", "ALTER ROW POLICY", "ALTER SETTINGS PROFILE",
    "ATTACH USER", "ATTACH ROLE", "ATTACH POLICY", "ATTACH PROFILE",
    "ATTACH QUOTA", "ATTACH ROW POLICY", "ATTACH SETTINGS PROFILE",
    "ATTACH TENANT", "ALTER TENANT", "CREATE TENANT", "TENANT", "TENANTS",
    "IDENTIFIED", "NOT IDENTIFIED", "DEFAULT ROLE", "SET DEFAULT ROLE",
    "SET ROLE", "SET ROLE DEFAULT", "SET DEFAULT", "SET NULL",
    "CURRENT_USER", "CURRENTUSER", "CURRENT ROLES", "ENABLED ROLES",
    "CURRENT QUOTA", "CURRENT GRANTS", "SHOW ACCESS", "SHOW CREATE",
    "SHOW GRANTS", "SHOW PRIVILEGES", "VALID UNTIL", "HOST", "NAME", "REALM",
    "ID", "IP", "LDAP", "KERBEROS", "SSL_CERTIFICATE", "JWT", "SSH_KEY",
    "HTTP", "READONLY", "CHANGEABLE_IN_READONLY", "IS_OBJECT_ID",
    "SHA256_HASH", "SHA256_PASSWORD", "DOUBLE_SHA1_HASH",
    "DOUBLE_SHA1_PASSWORD", "BCRYPT_HASH", "BCRYPT_PASSWORD", "PBKDF2_HASH",
    "PBKDF2_PASSWORD", "PLAINTEXT_PASSWORD", "NO_PASSWORD",
}

TCL_KEYWORDS = {
    "BEGIN TRANSACTION", "START TRANSACTION", "COMMIT", "ROLLBACK",
    "SET TRANSACTION SNAPSHOT", "CURRENT TRANSACTION", "CHECK TRANSACTION",
    "TRANSACTION", "SET FAKE TIME", "UNSET FAKE TIME",
}

UTILITY_KEYWORDS = {
    "EXPLAIN", "SET", "SHOW", "KILL", "SYSTEM", "BACKUP", "RESTORE",
    "WATCH", "FREEZE", "UNFREEZE", "FETCH", "FETCH PART", "FETCH PARTITION",
    "SUSPEND", "RESUME", "QUERY", "QUERY TREE", "SYNTAX", "PLAN", "AST",
    "PIPELINE", "ESTIMATE", "EXTENDED", "TEST", "DDLTASK", "MUTATION",
    "PART_MOVE_TO_SHARD", "OPTIMIZE TABLE", "TRACKING ONLY",
}

SELECT_CLAUSE_KEYWORDS = {
    "WITH", "SELECT", "FROM", "PREWHERE", "WHERE", "GROUP BY", "HAVING",
    "ORDER BY", "LIMIT", "OFFSET", "SETTINGS", "UNION", "DISTINCT",
    "DISTINCT ON", "ALL", "ANY", "TOP", "WITH FILL", "WITH TIES",
    "GROUPING SETS", "CUBE", "ROLLUP", "WINDOW", "QUALIFY", "OVER",
    "TOTALS", "SAMPLE", "SAMPLE BY", "FINAL", "ARRAY JOIN",
    "LEFT ARRAY JOIN", "AS", "ALIAS", "RECURSIVE", "WITH NAME", "FORMAT",
    "NULLS", "RESPECT NULLS", "IGNORE NULLS", "FIRST", "LAST", "ROWS", "ROW",
    "CURRENT ROW", "PRECEDING", "FOLLOWING", "UNBOUNDED", "RANGE", "PARTIAL",
    "BETWEEN", "NOT BETWEEN", "INTERPOLATE", "EMPTY", "EMPTY AS", "ONLY",
    "SKIP", "NO LIMITS", "EXCEPT", "INTERSECT", "EXCEPT TABLE",
    "EXCEPT TABLES", "EXCEPT DATABASE", "EXCEPT DATABASES", "BY", "TO",
    "ASC", "ASCENDING", "DESC", "DESCENDING", "GROUPS", "INTO OUTFILE",
    "AND STDOUT", "FROM INFILE", "VALUES", "USING", "ON",
}

JOIN_KEYWORDS = {
    "JOIN", "INNER", "LEFT", "RIGHT", "FULL", "CROSS", "OUTER", "ANTI",
    "SEMI", "ANY", "ALL", "ASOF", "GLOBAL", "GLOBAL IN", "GLOBAL NOT IN",
    "IN", "NOT IN", "IN PARTITION", "ON", "USING", "KEYED BY", "NOT KEYED",
    "KEY BY", "BIDIRECTIONAL", "HIERARCHICAL", "ARRAY JOIN",
    "LEFT ARRAY JOIN",
}

OPERATOR_KEYWORDS = {
    "AND", "OR", "NOT", "IS NULL", "IS NOT NULL", "IS NOT DISTINCT FROM",
    "IN", "NOT IN", "LIKE", "NOT LIKE", "ILIKE", "NOT ILIKE", "REGEXP",
    "MATCH", "FULLTEXT", "BETWEEN", "NOT BETWEEN", "CASE", "WHEN", "THEN",
    "ELSE", "END", "CAST", "TYPEOF", "DIV", "MOD", "FILTER", "OVER", "TRUE",
    "FALSE", "NULL", "COLLATE", "EXISTS", "INTERVAL", "ASSUME", "REFERENCES",
    "CONST", "CONSTRAINT", "NOT OVERRIDABLE", "OVERRIDABLE",
}

DATA_TYPE_KEYWORDS = {
    "CHAR", "CHAR VARYING", "CHARACTER", "CHARACTER VARYING",
    "CHARACTER LARGE OBJECT", "LARGE OBJECT", "VARYING", "DATE", "TIMESTAMP",
    "UNSIGNED", "SIGNED", "SIMPLE", "UUID", "DATA", "PRECISION",
}

TIME_UNIT_KEYWORDS = {
    "SECOND", "SECONDS", "MINUTE", "MINUTES", "HOUR", "HOURS", "DAY",
    "DAYS", "WEEK", "WEEKS", "MONTH", "MONTHS", "QUARTER", "QUARTERS",
    "YEAR", "YEARS", "MICROSECOND", "MICROSECONDS", "MILLISECOND",
    "MILLISECONDS", "NANOSECOND", "NANOSECONDS", "MCS", "MS", "NS",
    "INTERVAL", "SQL_TSI_DAY", "SQL_TSI_HOUR", "SQL_TSI_MICROSECOND",
    "SQL_TSI_MILLISECOND", "SQL_TSI_MINUTE", "SQL_TSI_MONTH",
    "SQL_TSI_NANOSECOND", "SQL_TSI_QUARTER", "SQL_TSI_SECOND",
    "SQL_TSI_WEEK", "SQL_TSI_YEAR",
}

DATE_TOKEN_KEYWORDS = {
    "D", "DD", "H", "HH", "M", "MM", "MI", "N", "Q", "QQ", "S", "SS", "WK",
    "WW", "YY", "YYYY",
}

DICTIONARY_KEYWORDS = {
    "DICTIONARY", "DICTIONARIES", "LAYOUT", "SOURCE", "LIFETIME", "RANGE",
    "HIERARCHICAL", "INJECTIVE", "BIDIRECTIONAL", "EXPRESSION", "EVENT",
    "EVENTS",
}

PARTITION_KEYWORDS = {
    "PART", "PARTITION", "PARTITIONS", "PARTITION BY", "SUBPARTITION",
    "SUBPARTITION BY", "SUBPARTITIONS", "DROP PART", "DROP PARTITION",
    "DROP DETACHED PART", "DROP DETACHED PARTITION", "UNDROP PART",
    "UNDROP PARTITION", "ATTACH PART", "ATTACH PARTITION", "DETACH PART",
    "DETACH PARTITION", "MOVE PART", "MOVE PARTITION", "MOVE",
    "REPLACE PARTITION", "FETCH PART", "FETCH PARTITION", "FORGET PARTITION",
    "FREEZE", "UNFREEZE", "TO DISK", "TO VOLUME", "TO TABLE", "TO SHARD",
    "FROM SHARD", "TO INNER UUID", "DATA INNER UUID", "METRICS INNER UUID",
    "TAGS INNER UUID", "DISK", "RECOMPRESS", "PART_MOVE_TO_SHARD",
}

ALTER_ACTION_KEYWORDS = {
    "ADD", "ADD COLUMN", "ADD CONSTRAINT", "ADD INDEX", "ADD PROJECTION",
    "ADD STATISTICS", "MODIFY", "MODIFY COLUMN", "MODIFY COMMENT",
    "MODIFY DEFINER", "MODIFY ORDER BY", "MODIFY QUERY", "MODIFY REFRESH",
    "MODIFY SAMPLE BY", "MODIFY STATISTICS", "MODIFY SETTING",
    "MODIFY SQL SECURITY", "MODIFY TTL", "RENAME COLUMN", "RENAME TO",
    "DROP COLUMN", "DROP CONSTRAINT", "DROP DEFAULT", "DROP INDEX",
    "DROP PROJECTION", "DROP STATISTICS", "CLEAR COLUMN", "CLEAR INDEX",
    "CLEAR PROJECTION", "CLEAR STATISTICS", "MATERIALIZE COLUMN",
    "MATERIALIZE INDEX", "MATERIALIZE PROJECTION", "MATERIALIZE STATISTICS",
    "MATERIALIZE TTL", "MATERIALIZE", "REMOVE", "REMOVE SAMPLE BY",
    "REMOVE TTL", "RESET SETTING", "REPLACE", "REPLACE PARTITION",
    "COMMENT COLUMN", "COMMENT", "ALTER COLUMN", "CHANGE", "FOREIGN KEY",
    "FOREIGN", "ON DELETE", "ON UPDATE", "ON VOLUME", "NO ACTION",
    "CASCADE", "RESTRICT", "SET NULL", "SET DEFAULT", "ENFORCED",
    "PERMISSIVE", "RESTRICTIVE", "VISIBLE", "INVISIBLE", "SALT", "DEPENDS ON",
    "APPEND", "PASTE", "APPLY DELETED MASK", "TAG", "TAGS", "STATISTICS",
    "GRANULARITY", "INDEX", "INDEXES", "INDICES", "PROJECTION",
    "PRIMARY KEY", "PRIMARY", "TTL", "ENGINE", "COMPRESSION", "CODEC", "STEP",
    "PERIODIC REFRESH", "MODIFY REFRESH", "REFRESH", "DEFINER", "INVOKER",
    "SQL SECURITY", "AFTER", "CLEANUP", "COLUMN", "COLUMNS", "LEVEL",
    "LESS THAN", "NEXT", "NONE",
}

SETTING_KEYWORDS = {
    "SETTINGS", "ENGINE", "CODEC", "COMPRESSION", "STORAGE", "DISK",
    "MEMORY", "READONLY", "PERMANENTLY", "TEMPORARY", "TEMPORARY TABLE",
    "PROFILE", "QUOTA", "DEFAULT", "DEFAULT DATABASE", "CHANGEABLE_IN_READONLY",
    "WITH_ITEMINDEX", "ALLOWED_LATENESS", "WATERMARK", "STRICTLY_ASCENDING",
    "LIGHTWEIGHT", "PERSISTENT", "PERSISTENT SEQUENTIAL", "EPHEMERAL",
    "EPHEMERAL SEQUENTIAL", "AUTO_INCREMENT", "base_backup",
    "cluster_host_ids", "NAMED COLLECTION", "FILESYSTEM CACHE",
    "FILESYSTEM CACHES", "TRACKING ONLY", "ZKPATH",
}

SHOW_KEYWORDS = {
    "SHOW", "SHOW TABLES", "SHOW COLUMNS", "SHOW FUNCTIONS", "SHOW INDEXES",
    "SHOW ENGINES", "SHOW PROCESSLIST", "SHOW CREATE", "SHOW SETTING",
    "SHOW ACCESS", "SHOW GRANTS", "SHOW PRIVILEGES", "DATABASES", "CLUSTERS",
    "DICTIONARIES", "TABLES", "MERGES", "METRICS", "TAGS", "EVENTS",
    "PARTITIONS", "SETTING",
}

MISC_KEYWORDS = {
    "IF EXISTS", "IF NOT EXISTS", "IF EMPTY", "OR REPLACE", "OR", "CASCADE",
    "RESTRICT", "CLUSTER", "CLUSTERS", "SERVER", "CN", "AZURE", "HDFS", "S3",
    "Protobuf", "URL", "FILE", "FIELDS", "FUNCTION", "VIEW", "LIVE", "KIND",
    "TYPE", "PREFIX", "STRICT", "SYNC", "ASYNC", "NO DELAY", "LOCAL",
    "GLOBAL", "LIST", "HASH", "LINEAR", "MAX", "MIN", "NAME", "TAG", "TAGS",
    "DEFINER", "INVOKER", "SQL SECURITY", "OVERRIDABLE", "NOT OVERRIDABLE",
    "PERMISSIVE", "RESTRICTIVE", "ENFORCED", "VISIBLE", "INVISIBLE",
    "BIDIRECTIONAL", "HIERARCHICAL", "INHERIT", "RANDOMIZED",
    "RANDOMIZE FOR", "PULL", "APPEND", "PASTE", "PIPELINE", "TEST", "SCHEME",
    "SAN", "WRITABLE", "SIGNED", "EVENT", "BOTH", "LEADING", "TRAILING",
    "FOR", "EVERY", "SPATIAL", "FULLTEXT", "MATCH", "bagexpansion",
    "DDLTASK", "ESTIMATE", "EXTENDED", "ASSUME", "INJECTIVE", "LIFETIME",
    "LAYOUT", "SOURCE", "RANGE", "EXPRESSION", "REALM", "ID", "HOST", "IP",
    "LDAP", "KERBEROS", "JWT", "HTTP", "UNSIGNED", "SIMPLE", "VARYING",
    "CHARACTER", "CHAR", "DATA", "UUID", "STORAGE", "PROFILE", "QUOTA",
    "DEFINER", "PERMANENTLY", "TEMPORARY", "COMMENT",
}


# =============================================================================
# Soft-reserved keywords (should not be used as bare identifiers)
# =============================================================================
SOFT_RESERVED_KEYWORDS = {
    "SELECT", "FROM", "WHERE", "GROUP BY", "ORDER BY", "HAVING", "LIMIT",
    "OFFSET", "JOIN", "ON", "USING", "AS", "DISTINCT", "ALL", "ANY", "UNION",
    "INSERT INTO", "VALUES", "DELETE", "UPDATE", "SET", "CREATE", "ALTER",
    "DROP", "TABLE", "DATABASE", "VIEW", "FUNCTION", "INDEX", "ENGINE",
    "AND", "OR", "NOT", "IN", "IS NULL", "IS NOT NULL", "LIKE", "BETWEEN",
    "CASE", "WHEN", "THEN", "ELSE", "END", "CAST", "EXISTS", "WITH", "BY",
    "TO", "PRIMARY KEY", "FOREIGN KEY", "CONSTRAINT", "DEFAULT", "COMMENT",
    "NULL", "TRUE", "FALSE",
}


# =============================================================================
# Category map for reporting
# =============================================================================
ALL_KEYWORD_CATEGORIES = {
    KeywordCategory.DML: DML_KEYWORDS,
    KeywordCategory.DDL: DDL_KEYWORDS,
    KeywordCategory.DCL: DCL_KEYWORDS,
    KeywordCategory.TCL: TCL_KEYWORDS,
    KeywordCategory.UTILITY: UTILITY_KEYWORDS,
    KeywordCategory.ACCESS: DCL_KEYWORDS,  # access-control subset of DCL
    KeywordCategory.SELECT_CLAUSE: SELECT_CLAUSE_KEYWORDS,
    KeywordCategory.JOIN: JOIN_KEYWORDS,
    KeywordCategory.OPERATOR: OPERATOR_KEYWORDS,
    KeywordCategory.DATA_TYPE: DATA_TYPE_KEYWORDS,
    KeywordCategory.TIME_UNIT: TIME_UNIT_KEYWORDS,
    KeywordCategory.DATE_TOKEN: DATE_TOKEN_KEYWORDS,
    KeywordCategory.DICTIONARY: DICTIONARY_KEYWORDS,
    KeywordCategory.PARTITION: PARTITION_KEYWORDS,
    KeywordCategory.ALTER_ACTION: ALTER_ACTION_KEYWORDS,
    KeywordCategory.SETTING: SETTING_KEYWORDS,
    KeywordCategory.SHOW: SHOW_KEYWORDS,
    KeywordCategory.MISC: MISC_KEYWORDS,
}


def is_keyword(text: str) -> bool:
    """Return True if text (case-insensitive) is a known ClickHouse keyword."""
    if not text:
        return False
    return text.upper() in _KEYWORDS_UPPER


def is_reserved_keyword(text: str) -> bool:
    """Return True if text is a soft-reserved keyword (should not be a bare identifier)."""
    if not text:
        return False
    return text.upper() in {k.upper() for k in SOFT_RESERVED_KEYWORDS}


def get_keyword_category(text: str):
    """Return the KeywordCategory for a keyword, or None if unknown."""
    if not text:
        return None
    up = text.upper()
    for cat, kw_set in ALL_KEYWORD_CATEGORIES.items():
        if up in {k.upper() for k in kw_set}:
            return cat
    return None


def get_all_keywords() -> list:
    """Return a sorted list of all keywords (original case)."""
    return sorted(ALL_KEYWORDS)


def get_keyword_count() -> int:
    """Return the total number of unique keywords."""
    return len(ALL_KEYWORDS)


if __name__ == "__main__":
    kws = get_all_keywords()
    print(f"Total ClickHouse 24.8 keywords: {len(kws)}")
    print(f"Soft-reserved keywords: {len(SOFT_RESERVED_KEYWORDS)}")
    print("\nKeywords by category:")
    for cat, kw_set in ALL_KEYWORD_CATEGORIES.items():
        print(f"  {cat.value}: {len(kw_set)}")
