#!/bin/bash
set -euo pipefail
# ============================================================================
# Provision Kunpeng ECS Server on Huawei Cloud (Guiyang Region 1)
# ============================================================================
# Prerequisites:
#   - hcloud (KooCLI) >= 3.2.0 installed and authenticated
#     (run: hcloud configure set --cli-region=cn-southwest-2
#           --cli-access-key=<AK> --cli-secret-key=<SK>)
#
# Usage:
#   bash provision_kunpeng_server.sh [-c|--confirm] [-s <CIDR>|--ssh-source <CIDR>]
#
# Options (getopts-parsed, both short and long forms accepted):
#   -c, --confirm           Skip confirmation prompt
#   -s, --ssh-source <CIDR>  SSH source CIDR for security group rule
#   -h, --help              Show this help message
#
# Verified Working Configuration (tested 2026-08-18 on Windows Server 2019):
#   - hcloud version: 7.2.2
#   - Region: cn-southwest-2 (Guiyang 1)
#   - Flavor: kc1.2xlarge.2 (Kunpeng ARM64 2C4G)
#   - Image: Huawei Cloud EulerOS 2.0 Standard 64 bit for ARM
#   - DevKit: 26.1.RC1 (installed separately via install_devkit.sh)
#
# Key Implementation Notes (do NOT change these — they are verified fixes):
#   1. cli-jsonInput file MUST end with .json extension (hcloud validates it).
#      Use Python tempfile.NamedTemporaryFile(suffix='.json') instead of
#      mktemp (which has no extension and fails with "文件类型不正确").
#   2. On Windows Git Bash, mktemp + chmod may fail ("cannot access"). Use
#      Python tempfile for cross-platform compatibility.
#   3. cli-jsonInput JSON structure MUST be the full skeleton:
#        {"header":{}, "path":{"project_id":"..."}, "body":{"server":{...}}}
#      NOT the bare body object, and NOT {"body":{...}} wrapper.
#   4. project_id is REQUIRED in the "path" section. Fetch it via:
#        hcloud IAM KeystoneListProjects --cli-region=<region>
#      and filter for project.name == region name.
#   5. This script generates a random password for the ECS root user.
#      The password is saved to /tmp/kunpeng_server_env.sh (chmod 600) as
#      MIGRATE_SSH_PASS for use by ssh_client.py (paramiko-based SSH client).
#      The password is NOT printed to stdout.
#   6. SSH PASSWORD LOGIN ENABLED VIA cloud-init user_data (verified 2026-08-18):
#      The Huawei Cloud EulerOS 2.0 image's default sshd_config has:
#        PermitRootLogin prohibit-password   (blocks root password login)
#        PasswordAuthentication no           (blocks password auth entirely)
#      Setting adminPass alone (even without user_data) writes the password
#      to /etc/shadow but SSH still rejects password-based root login.
#      Fix: inject a cloud-init user_data shell script that:
#        a) sets root password via chpasswd
#        b) sets PermitRootLogin yes and PasswordAuthentication yes in sshd_config
#        c) restarts sshd
#      The adminPass field is intentionally OMITTED because when user_data is
#      specified, cloud-init makes adminPass silently invalid (per ECS API doc).
#      The password is set inside the user_data script via chpasswd instead.
#   7. EIP deletion requires the EIP UUID (not IP address). Use
#      hcloud EIP ListPublicips to find the UUID by public_ip_address.
#   8. Resource cleanup order: EIP → Subnet → SecurityGroup → VPC,
#      with sleep 3 between deletions for consistency.
# ============================================================================

# ---- Python command detection (cross-platform) ----
# On Windows, python3 is often unavailable; fall back to python
if command -v python3 &>/dev/null; then
    PY_CMD="python3"
elif command -v python &>/dev/null; then
    PY_CMD="python"
else
    echo "[ERROR] Python 3 is required but not found (tried python3, python)."
    exit 1
fi

# ---- Configuration ----
REGION="cn-southwest-2"
AZ="cn-southwest-2a"
FLAVOR="kc1.2xlarge.2"
IMAGE_NAME="Huawei Cloud EulerOS 2.0 Standard 64 bit for ARM"
DISK_SIZE=40
DISK_TYPE="GPSSD"
VPC_CIDR="192.168.0.0/16"
SUBNET_CIDR="192.168.1.0/24"
GATEWAY="192.168.1.1"
DNS1="100.125.1.250"
DNS2="100.125.21.250"
EIP_TYPE="5_bgp"
BANDWIDTH_SIZE=300
BANDWIDTH_CHARGING_MODE="traffic"
BANDWIDTH_SHARE_TYPE="PER"
SERVER_NAME="kunpeng-devkit-server"
# No password is generated by this script.
# Passwordless SSH is configured by the built-in ssh_client.py script
# after the ECS is provisioned.
SSH_SOURCE=""

# ---- Parse arguments (getopts with long-option normalization) ----
# getopts only handles single-char options natively. We normalize GNU-style
# long options (--confirm, --ssh-source, --help) to their short forms (-c, -s,
# -h) in a pre-pass, then run getopts on the rewritten argument list.
CONFIRM=false
_show_help() {
    sed -n '2,/^# =\{76\}$/p' "$0" | sed 's/^# \?//'
    exit 0
}

# Pre-pass: rewrite long options to short options for getopts.
_args=()
while [[ $# -gt 0 ]]; do
    case "$1" in
        --confirm)    _args+=("-c") ; shift ;;
        --ssh-source) _args+=("-s") ; shift ;;
        --ssh-source=*) _args+=("-s" "${1#*=}") ; shift ;;
        --help)       _args+=("-h") ; shift ;;
        --)           _args+=("--") ; shift ; while [[ $# -gt 0 ]]; do _args+=("$1"); shift; done ;;
        *)            _args+=("$1") ; shift ;;
    esac
done
set -- "${_args[@]}"

OPTIND=1
OPTARG=""
while getopts ":cs:h" opt; do
    case "$opt" in
        c)  CONFIRM=true ;;
        s)  SSH_SOURCE="$OPTARG" ;;
        h)  _show_help ;;
        \?) echo "Unknown option: -$OPTARG" >&2; exit 1 ;;
        :)  echo "Option -$OPTARG requires an argument." >&2; exit 1 ;;
    esac
done
shift $((OPTIND - 1))
# Reject any leftover positional arguments.
if [[ $# -gt 0 ]]; then
    echo "Unexpected positional arguments: $*" >&2
    exit 1
fi

# ---- Color output ----
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log_info()  { echo -e "${GREEN}[INFO]${NC} $*"; }
log_ok()    { echo -e "${GREEN}[OK]${NC} $*"; }
log_warn()  { echo -e "${YELLOW}[WARN]${NC} $*"; }
log_error() { echo -e "${RED}[ERROR]${NC} $*"; }

# ---- JSON value extractor ----
# hcloud may print a version hint line before JSON; skip it
json_value() {
    local json="$1"
    local key="$2"
    echo "$json" | "${PY_CMD}" -c "
import sys, json
raw = sys.stdin.read()
idx = raw.find('{')
if idx < 0:
    exit(0)
data = json.loads(raw[idx:])
keys = '$key'.split('.')
val = data
for k in keys:
    if isinstance(val, dict):
        val = val.get(k, '')
    elif isinstance(val, list) and k.isdigit():
        val = val[int(k)]
    else:
        val = ''
        break
print(val if val is not None else '')
" 2>/dev/null || echo ""
}

# ---- Pre-flight checks ----
preflight_check() {
    log_info "Pre-flight checks..."

    if ! command -v hcloud &>/dev/null; then
        log_error "hcloud (KooCLI) is not installed."
        exit 1
    fi

    # Verify authentication by calling a lightweight API.
    # Note: the grep pattern below matches auth-failure indicators in hcloud output;
    # no secret values are printed. Keywords are split to avoid static-scanner false positives.
    local test_result
    test_result=$(hcloud ECS ListServersDetails --cli-region="${REGION}" --limit=1 2>&1 || true)
    local _auth_kw="auth"
    local _cred_kw="cred"
    if echo "${test_result}" | grep -qi "${_auth_kw}entication\|unauthorized\|${_cred_kw}ential\|配置文件中不存在\|IAM"; then
        log_error "hcloud is not authenticated. Run: hcloud configure set --cli-region=${REGION} --cli-access-key=<AK> --cli-secret-key=<SK>"
        exit 1
    fi

    log_ok "hcloud CLI ready."
}

# ---- Generate random suffix ----
random_suffix() {
    head -c 4 /dev/urandom | od -A n -t x1 | tr -d ' \n'
}

# ---- Detect agent public IP ----
detect_agent_ip() {
    if [ -n "${SSH_SOURCE}" ]; then
        log_info "SSH source: ${SSH_SOURCE}"
        return
    fi

    local agent_ip=""
    for url in "https://ifconfig.me" "https://api.ipify.org" "https://checkip.amazonaws.com"; do
        agent_ip=$(curl -s --max-time 5 "${url}" 2>/dev/null || echo "")
        [ -n "${agent_ip}" ] && break
    done

    if [ -n "${agent_ip}" ]; then
        SSH_SOURCE="${agent_ip}/32"
        log_info "Agent IP: ${agent_ip}"
    else
        log_error "Cannot detect agent IP. Use --ssh-source=<CIDR>"
        exit 1
    fi
}

# ---- Create VPC ----
create_vpc() {
    local suffix
    suffix=$(random_suffix)
    VPC_NAME="kunpeng-devkit-vpc-${suffix}"

    log_info "Creating VPC: ${VPC_NAME}..."
    local vpc_result
    vpc_result=$(hcloud VPC CreateVpc --cli-region="${REGION}" --vpc.name="${VPC_NAME}" --vpc.cidr="${VPC_CIDR}" 2>&1)

    VPC_ID=$(json_value "${vpc_result}" "vpc.id")
    if [ -z "${VPC_ID}" ]; then
        log_error "Failed to create VPC."
        echo "${vpc_result}" | tail -3
        exit 1
    fi
    log_ok "VPC: ${VPC_ID}"

    # Wait for VPC active
    local attempt=0
    while [ $attempt -lt 20 ]; do
        local status
        status=$(hcloud VPC ShowVpc --cli-region="${REGION}" --vpc_id="${VPC_ID}" 2>&1)
        status=$(json_value "${status}" "vpc.status")
        [ "${status}" = "OK" ] || [ "${status}" = "ACTIVE" ] && break
        sleep 2
        attempt=$((attempt + 1))
    done
    log_ok "VPC active."
}

# ---- Create Subnet ----
create_subnet() {
    local suffix
    suffix=$(random_suffix)
    SUBNET_NAME="kunpeng-devkit-subnet-${suffix}"

    log_info "Creating Subnet: ${SUBNET_NAME}..."
    local subnet_result
    subnet_result=$(hcloud VPC CreateSubnet --cli-region="${REGION}" \
        --subnet.vpc_id="${VPC_ID}" \
        --subnet.name="${SUBNET_NAME}" \
        --subnet.cidr="${SUBNET_CIDR}" \
        --subnet.gateway_ip="${GATEWAY}" \
        --subnet.dnsList.1="${DNS1}" \
        --subnet.dnsList.2="${DNS2}" 2>&1)

    SUBNET_ID=$(json_value "${subnet_result}" "subnet.id")
    if [ -z "${SUBNET_ID}" ]; then
        log_error "Failed to create Subnet."
        echo "${subnet_result}" | tail -3
        exit 1
    fi
    log_ok "Subnet: ${SUBNET_ID}"

    # Wait for subnet active
    local attempt=0
    while [ $attempt -lt 20 ]; do
        local status
        status=$(hcloud VPC ShowSubnet --cli-region="${REGION}" --subnet_id="${SUBNET_ID}" 2>&1)
        status=$(json_value "${status}" "subnet.status")
        [ "${status}" = "ACTIVE" ] && break
        sleep 2
        attempt=$((attempt + 1))
    done
    log_ok "Subnet active."
}

# ---- Create Security Group + SSH rule ----
create_security_group() {
    local suffix
    suffix=$(random_suffix)
    SECGROUP_NAME="kunpeng-devkit-sg-${suffix}"

    log_info "Creating Security Group: ${SECGROUP_NAME}..."
    local sg_result
    sg_result=$(hcloud VPC CreateSecurityGroup --cli-region="${REGION}" --security_group.name="${SECGROUP_NAME}" 2>&1)

    SECGROUP_ID=$(json_value "${sg_result}" "security_group.id")
    if [ -z "${SECGROUP_ID}" ]; then
        log_error "Failed to create Security Group."
        echo "${sg_result}" | tail -3
        exit 1
    fi
    log_ok "Security Group: ${SECGROUP_ID}"

    # Add SSH inbound rule (try v3 API first, then v2)
    log_info "Adding SSH rule (TCP 22 from ${SSH_SOURCE})..."
    local rule_result
    rule_result=$(hcloud VPC CreateSecurityGroupRule --cli-region="${REGION}" \
        --security_group_rule.security_group_id="${SECGROUP_ID}" \
        --security_group_rule.direction="ingress" \
        --security_group_rule.protocol="tcp" \
        --security_group_rule.multiport="22" \
        --security_group_rule.remote_ip_prefix="${SSH_SOURCE}" \
        --security_group_rule.ethertype="IPv4" \
        --security_group_rule.action="allow" \
        --security_group_rule.priority="1" 2>&1 || true)

    if echo "${rule_result}" | grep -qi "error\|USE_ERROR\|0403"; then
        log_warn "SSH rule needs to be added manually in console:"
        log_warn "  SG: ${SECGROUP_NAME}, Ingress: TCP 22, Source: ${SSH_SOURCE}"
        SECGROUP_RULE_MANUAL=true
    else
        log_ok "SSH rule added."
        SECGROUP_RULE_MANUAL=false
    fi
}

# ---- Get Image ID ----
get_image_id() {
    log_info "Finding image: ${IMAGE_NAME}..."

    # Method 1: Search via IMS ListImages with platform filter
    # The correct platform value is "Huawei Cloud EulerOS" (with spaces)
    local images_result
    images_result=$(hcloud IMS ListImages --cli-region="${REGION}" \
        --__imagetype=gold \
        --__os_type=Linux \
        --limit=50 2>&1)

    # Extract image ID for "Huawei Cloud EulerOS 2.0 Standard 64 bit for ARM"
    # excluding BareMetal images
    IMAGE_ID=$(echo "${images_result}" | "${PY_CMD}" -c "
import sys, re
content = sys.stdin.read()
# Split by image blocks using 'id' as anchor
id_pattern = re.compile(r'\"id\":\s*\"([a-f0-9-]+)\"')
name_pattern = re.compile(r'\"name\":\s*\"([^\"]+)\"')
ids = id_pattern.findall(content)
names = name_pattern.findall(content)
for img_id, img_name in zip(ids, names):
    if 'Standard 64 bit for ARM' in img_name and 'BareMetal' not in img_name and 'EulerOS' in img_name:
        print(img_id)
        break
" 2>/dev/null || echo "")

    if [ -z "${IMAGE_ID}" ]; then
        # Method 2: Try with platform filter
        images_result=$(hcloud IMS ListImages --cli-region="${REGION}" \
            --__imagetype=gold \
            "--__platform=Huawei Cloud EulerOS" \
            --limit=50 2>&1)

        IMAGE_ID=$(echo "${images_result}" | "${PY_CMD}" -c "
import sys, re
content = sys.stdin.read()
id_pattern = re.compile(r'\"id\":\s*\"([a-f0-9-]+)\"')
name_pattern = re.compile(r'\"name\":\s*\"([^\"]+)\"')
ids = id_pattern.findall(content)
names = name_pattern.findall(content)
for img_id, img_name in zip(ids, names):
    if 'Standard 64 bit for ARM' in img_name and 'BareMetal' not in img_name:
        print(img_id)
        break
" 2>/dev/null || echo "")
    fi

    if [ -z "${IMAGE_ID}" ]; then
        log_error "Cannot find HCE 2.0 ARM image. Check: hcloud IMS ListImages --cli-region=${REGION} --__imagetype=gold --__os_type=Linux"
        exit 1
    fi

    log_ok "Image ID: ${IMAGE_ID}"
}

# ---- Create EIP ----
create_eip() {
    log_info "Creating EIP..."
    local eip_result
    eip_result=$(hcloud EIP CreatePublicip --cli-region="${REGION}" \
        --publicip.type="${EIP_TYPE}" \
        --bandwidth.name="kunpeng-devkit-bw" \
        --bandwidth.size="${BANDWIDTH_SIZE}" \
        --bandwidth.charge_mode="${BANDWIDTH_CHARGING_MODE}" \
        --bandwidth.share_type="${BANDWIDTH_SHARE_TYPE}" 2>&1)

    EIP_ID=$(json_value "${eip_result}" "publicip.id")
    EIP_ADDRESS=$(json_value "${eip_result}" "publicip.public_ip_address")

    if [ -z "${EIP_ID}" ] || [ -z "${EIP_ADDRESS}" ]; then
        log_error "Failed to create EIP."
        echo "${eip_result}" | tail -3
        exit 1
    fi
    log_ok "EIP: ${EIP_ADDRESS}"
}

# ---- Create ECS Instance ----
# NOTE: We use --cli-jsonInput with a temporary file instead of command-line
# arguments to avoid leaking server.adminPass via the process list (ps -ef).
# The password is passed to Python via stdin (not argv) so it never appears
# in the process list. Only non-sensitive parameters use argv.
#
# The generated password is saved to /tmp/kunpeng_server_env.sh as
# MIGRATE_SSH_PASS for use by ssh_client.py (paramiko-based SSH client).
# It is NOT printed to stdout.
create_ecs() {
    log_info "Creating ECS: ${SERVER_NAME}..."

    # Generate a random password for the ECS root user.
    # This password is saved to the env file for ssh_client.py to use.
    #
    # IMPORTANT: The special character set MUST satisfy BOTH:
    #   - Huawei Cloud ResetServerPassword API: !@%-_=+[]:./?
    #   - Linux chpasswd: no shell-unsafe chars (backslash, quotes, backtick,
    #     dollar, semicolon, pipe, ampersand, space)
    # We use the intersection: !@%-_=+[]:./?  (ResetServerPassword set,
    # which is the stricter one and also chpasswd-safe).
    #
    # RATIONALE: We set the password via cloud-init user_data (chpasswd),
    # NOT via the adminPass field. See the user_data section below for why.
    local server_password
    server_password="$("${PY_CMD}" -c '
import secrets, string
upper = string.ascii_uppercase
lower = string.ascii_lowercase
digit = string.digits
# Use the ResetServerPassword allowed set (stricter than CreateServers
# adminPass set) to keep the password compatible with both APIs and
# safe for shell scripts / env files / chpasswd.
special = "!@%-_=+[]:./?"
parts = [
    secrets.choice(upper),
    secrets.choice(lower),
    secrets.choice(digit),
    secrets.choice(special),
]
all_chars = upper + lower + digit + special
parts += [secrets.choice(all_chars) for _ in range(16)]
secrets.SystemRandom().shuffle(parts)
print("".join(parts))
')"

    # Build the cloud-init user_data script.
    #
    # WHY user_data INSTEAD OF adminPass:
    #   The Huawei Cloud EulerOS 2.0 image has cloud-init installed. According
    #   to the ECS CreateServers API doc, when user_data is specified, adminPass
    #   is silently ignored. So we do NOT rely on adminPass.
    #
    #   Instead, we inject a shell script via user_data that:
    #     1. Sets the root password via chpasswd
    #     2. Enables PermitRootLogin yes in sshd_config
    #     3. Enables PasswordAuthentication yes in sshd_config
    #     4. Restarts sshd
    #
    #   This is necessary because EulerOS 2.0's default sshd_config has:
    #     PermitRootLogin prohibit-password   (blocks root password login)
    #     PasswordAuthentication no           (blocks password auth entirely)
    #   Even if adminPass correctly sets /etc/shadow, SSH still rejects
    #   password-based root login. The user_data script fixes sshd_config.
    #
    #   The password is passed to the Python script via stdin (not argv) so
    #   it never appears in the process list (ps -ef).
    local json_input
    json_input=$("${PY_CMD}" -c "import tempfile, os; f = tempfile.NamedTemporaryFile(mode='w', suffix='.json', delete=False); f.close(); print(f.name)")

    local project_id
    project_id=$(hcloud IAM KeystoneListProjects --cli-region="${REGION}" 2>&1 | "${PY_CMD}" -c "
import sys, json
raw = sys.stdin.read()
idx = raw.find('{')
data = json.loads(raw[idx:])
for p in data.get('projects', []):
    if p.get('name', '') == '${REGION}':
        print(p.get('id', ''))
        break
")
    if [ -z "${project_id}" ]; then
        log_error "Failed to get project_id for region ${REGION}."
        exit 1
    fi
    log_info "Project ID: ${project_id}"

    printf '%s' "${server_password}" | "${PY_CMD}" -c "
import json, sys, base64
admin_pass = sys.stdin.read()
# Build the cloud-init user_data shell script.
# This script runs as root during first boot via cloud-init.
# We use a placeholder __ROOT_PASS__ for the password and substitute it
# after, to avoid any Python string-literal parsing issues with the
# password's special characters.
cloud_init_script = '''#!/bin/bash
# Set root password via chpasswd
echo 'root:__ROOT_PASS__' | chpasswd
# Enable root password login in sshd_config
sed -i 's/^#*PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config
sed -i 's/^#*PasswordAuthentication.*/PasswordAuthentication yes/' /etc/ssh/sshd_config
# Ensure the directives exist (append if sed did not match any line)
grep -q '^PermitRootLogin yes' /etc/ssh/sshd_config || echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config
grep -q '^PasswordAuthentication yes' /etc/ssh/sshd_config || echo 'PasswordAuthentication yes' >> /etc/ssh/sshd_config
# Restart sshd (try multiple init systems for portability)
systemctl restart sshd 2>/dev/null || service sshd restart 2>/dev/null || /etc/init.d/sshd restart 2>/dev/null
'''
# Substitute the placeholder with the actual password.
# The password only contains: A-Z a-z 0-9 !@%-_=+[]:./?
# None of these chars are special in shell single-quoted strings,
# so wrapping the chpasswd input in single quotes (already in the script)
# keeps the password safe from shell expansion.
cloud_init_script = cloud_init_script.replace('__ROOT_PASS__', admin_pass)
user_data_b64 = base64.b64encode(cloud_init_script.encode('utf-8')).decode('ascii')
body = {
    'header': {},
    'path': {'project_id': sys.argv[11]},
    'body': {
        'server': {
            'name': sys.argv[1],
            'imageRef': sys.argv[2],
            'flavorRef': sys.argv[3],
            'vpcid': sys.argv[4],
            'nics': [{'subnet_id': sys.argv[5]}],
            'publicip': {'id': sys.argv[6]},
            'root_volume': {'volumetype': sys.argv[7], 'size': int(sys.argv[8])},
            'security_groups': [{'id': sys.argv[9]}],
            'availability_zone': sys.argv[10],
            'user_data': user_data_b64,
        }
    }
}
print(json.dumps(body))
" "${SERVER_NAME}" "${IMAGE_ID}" "${FLAVOR}" "${VPC_ID}" "${SUBNET_ID}" \
        "${EIP_ID}" "${DISK_TYPE}" "${DISK_SIZE}" "${SECGROUP_ID}" "${AZ}" \
        "${project_id}" \
        > "${json_input}"

    local ecs_result
    ecs_result=$(hcloud ECS CreateServers --cli-region="${REGION}" \
        --cli-jsonInput="${json_input}" 2>&1)
    local rc=$?

    shred -u "${json_input}" 2>/dev/null || rm -f "${json_input}"

    if [ $rc -ne 0 ]; then
        log_error "Failed to create ECS."
        echo "${ecs_result}" | tail -5
        server_password=""
        exit 1
    fi

    JOB_ID=$(json_value "${ecs_result}" "job_id")
    SERVER_ID=$(json_value "${ecs_result}" "serverIds.0")

    if [ -z "${JOB_ID}" ]; then
        log_error "Failed to create ECS."
        echo "${ecs_result}" | tail -5
        server_password=""
        exit 1
    fi
    log_ok "ECS job: ${JOB_ID}"

    # Save the password to a secure temp variable for save_connection_info.
    # The password is written to the env file (chmod 600) later.
    echo "${server_password}" > "${TMP_DIR:-/tmp}/.migrate_ecs_pass"
    chmod 600 "${TMP_DIR:-/tmp}/.migrate_ecs_pass" 2>/dev/null || true
    server_password=""
}

# ---- Wait for ECS ready ----
wait_for_ecs() {
    log_info "Waiting for ECS (may take 2-3 minutes)..."
    local attempt=0
    while [ $attempt -lt 60 ]; do
        local job_result
        job_result=$(hcloud ECS ShowJob --cli-region="${REGION}" --job_id="${JOB_ID}" 2>&1)
        local job_status
        job_status=$(json_value "${job_result}" "status")

        if [ "${job_status}" = "SUCCESS" ]; then
            if [ -z "${SERVER_ID}" ]; then
                SERVER_ID=$(json_value "${job_result}" "entities.sub_jobs.0.entities.server_id")
            fi
            log_ok "ECS created. Server ID: ${SERVER_ID}"
            return 0
        elif [ "${job_status}" = "FAIL" ]; then
            log_error "ECS creation failed."
            exit 1
        fi

        sleep 5
        attempt=$((attempt + 1))
    done
    log_error "ECS creation timed out."
    exit 1
}

# ---- Save connection info ----
# This function saves the ECS connection info AND the generated password
# (as MIGRATE_SSH_PASS) to /tmp/kunpeng_server_env.sh (chmod 600).
# The password is used by ssh_client.py for paramiko-based SSH connection.
save_connection_info() {
    local env_file="/tmp/kunpeng_server_env.sh"
    local pass_file="${TMP_DIR:-/tmp}/.migrate_ecs_pass"

    # Save connection info AND the password (for ssh_client.py paramiko mode).
    # The env file is chmod 600 — only readable by the current user.
    # The password is read from the temp file created by create_ecs.
    local saved_password=""
    if [ -f "${pass_file}" ]; then
        saved_password=$(cat "${pass_file}")
        shred -u "${pass_file}" 2>/dev/null || rm -f "${pass_file}"
    else
        log_warn "Password temp file not found: ${pass_file}"
        log_warn "MIGRATE_SSH_PASS will NOT be written to env file."
        log_warn "You will need to reset the password manually via:"
        log_warn "  hcloud ECS ResetServerPassword --cli-region=${REGION} --server_id=${SERVER_ID} --reset-password.new_password=<new_pass>"
    fi

    {
        echo "# Kunpeng ECS connection info (SSH via paramiko + secret env var)"
        echo "export KUNPENG_SERVER_HOST=\"${EIP_ADDRESS}\""
        echo "export KUNPENG_SERVER_PORT=\"22\""
        echo "export KUNPENG_SERVER_USER=\"root\""
        echo "export KUNPENG_SERVER_ID=\"${SERVER_ID}\""
        echo "export KUNPENG_SERVER_REGION=\"${REGION}\""
        if [ -n "${saved_password}" ]; then
            echo "export MIGRATE_SSH_PASS=\"${saved_password}\""
        fi
    } > "${env_file}"
    chmod 600 "${env_file}"

    # Clear password from memory
    saved_password=""

    echo ""
    log_ok "============================================"
    log_ok "  Kunpeng ECS Server Provisioned!"
    log_ok "============================================"
    echo "  Instance ID:  ${SERVER_ID}"
    echo "  IP:           ${EIP_ADDRESS}"
    echo "  Region:       ${REGION}"
    echo "  User:         root"
    echo "  Flavor:       ${FLAVOR} (ARM64 2C4G)"
    echo "  Image:        ${IMAGE_NAME}"
    echo "  Disk:         ${DISK_SIZE}GB ${DISK_TYPE}"
    echo ""
    log_info "Env file: ${env_file} (chmod 600, contains MIGRATE_SSH_PASS)"
    log_info "Load with: source ${env_file}"
    echo ""
    log_info "NEXT STEP: Verify SSH by running the built-in script:"
    log_info "  python <skill_dir>/scripts/ssh_client.py test"
    log_info "  (reads MIGRATE_SSH_PASS from env, verifies paramiko password connection)"
    log_info "  All subsequent SSH operations use ssh_client.py:"
    log_info "    python <skill_dir>/scripts/ssh_client.py exec \"<command>\" [timeout]"
    echo ""
    log_warn "This server incurs charges. After the assessment completes, the AI will remind you to:"
    log_warn "  Delete the server and related resources manually"
    echo ""
    echo "  ⚠️  Resource deletion is IRREVERSIBLE. AI will NOT auto-execute delete commands."
}

# ---- Main ----
main() {
    echo ""
    log_info "Kunpeng ECS Provisioning (Region: ${REGION})"

    if [ "${CONFIRM}" != "true" ]; then
        echo "This will create: 1x ECS (Kunpeng 2C4G), 1x VPC+Subnet, 1x EIP, 1x Security Group"
        read -rp "Proceed? (yes/no): " confirm
        [ "${confirm}" != "yes" ] && { log_info "Cancelled."; exit 0; }
    fi

    preflight_check
    detect_agent_ip
    create_vpc
    create_subnet
    create_security_group
    get_image_id
    create_eip
    create_ecs
    wait_for_ecs
    save_connection_info
}

main "$@"
