#!/usr/bin/env python3
# coding: utf-8
"""
Huawei Cloud Flexus L Instance One-Click Hermes Deployment Command Line Tool

Use Huawei Cloud SDK for Hermes deployment and configuration management.

Commands:
    deploy  - One-click deploy Hermes to Huawei Cloud Flexus L Instance
    maas    - Configure ModelArts large model based on deployed Hermes instance
    channel - Configure bot channels based on deployed Hermes instance
    
Parameters:
    --ak: Huawei Cloud Access Key (required)
    --sk: Huawei Cloud Secret Key (required)
    --security-token: Security token for temporary credentials (optional)
"""

import argparse
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from scripts.utils import REGION_IDS
from scripts.deploy import do_deploy_hermes
from scripts.models import do_install_maas
from scripts.channels import do_install_channel
from scripts.gateway import do_restart_gateway
from scripts.lib import coc_query_execution


def show_main_menu():
    """Display main menu for user to select operation type"""
    print("=" * 60)
    print("          Hermes One-Click Deployment Tool")
    print("=" * 60)
    print("Please select the operation you want to perform:")
    print("")
    print("  1. One-click deploy Hermes to Huawei Cloud Flexus L Instance")
    print("  2. Configure ModelArts large model on deployed Hermes instance")
    print("  3. Configure bot channels on deployed Hermes instance")
    print("  4. Restart Hermes Gateway")
    print("  5. Query COC script execution result")
    print("  0. Exit")
    print("")
    print("=" * 60)
    
    while True:
        try:
            choice = input("Please enter your choice (0-5): ")
            choice = int(choice)
            if choice in [0, 1, 2, 3, 4, 5]:
                return choice
            else:
                print("Invalid input, please enter a number between 0-5")
        except ValueError:
            print("Invalid input, please enter a number")


def main():
    parser = argparse.ArgumentParser(
        description="Huawei Cloud Flexus L Instance One-Click Hermes Deployment",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Interactive mode (shows menu)
  python scripts/caller.py

  # One-click deploy Hermes to Flexus L Instance using permanent AK/SK
  python scripts/caller.py deploy --ak <your_ak> --sk <your_sk> --name my-hermes --region cn-north-4

  # One-click deploy using temporary AK/SK and security-token
  python scripts/caller.py deploy --ak <temp_ak> --sk <temp_sk> --security-token <security_token> --name my-hermes --region cn-north-4

  # Configure ModelArts large model using permanent AK/SK
  python scripts/caller.py maas --ak <your_ak> --sk <your_sk> --resource-id <instance_id> --region-id cn-north-4 --api-key <your_api_key> --model-name deepseek-v3.2

  # Configure ModelArts model using temporary credentials
  python scripts/caller.py maas --ak <temp_ak> --sk <temp_sk> --security-token <security_token> --resource-id <instance_id> --region-id cn-north-4 --api-key <your_api_key> --model-name deepseek-v3.2

  # Configure Feishu bot channel using permanent AK/SK
  python scripts/caller.py channel --ak <your_ak> --sk <your_sk> --resource-id <instance_id> --region-id cn-north-4 --bot-platform feishu --feishu-app-id <app_id> --feishu-app-secret <app_secret>

  # Configure WeCom bot channel using temporary credentials
  python scripts/caller.py channel --ak <temp_ak> --sk <temp_sk> --security-token <security_token> --resource-id <instance_id> --region-id cn-north-4 --bot-platform wecom --wecom-bot-id <bot_id> --wecom-secret <secret>

  # Query COC script execution result using permanent AK/SK
  python scripts/caller.py query --ak <your_ak> --sk <your_sk> --execute-uuid <execute_uuid>

  # Query execution result using temporary credentials
  python scripts/caller.py query --ak <temp_ak> --sk <temp_sk> --security-token <security_token> --execute-uuid <execute_uuid>
        """,
    )

    subparsers = parser.add_subparsers(dest='command', help='Available commands')

    deploy_parser = subparsers.add_parser('deploy', help='One-click deploy Hermes to Flexus L Instance')
    deploy_parser.add_argument('--ak', required=True, help='Huawei Cloud AK (required)')
    deploy_parser.add_argument('--sk', required=True, help='Huawei Cloud SK (required)')
    deploy_parser.add_argument('--security-token', help='Security token for temporary credentials (optional)')
    deploy_parser.add_argument('--name', help='Instance name (optional, auto-generated by default)')
    deploy_parser.add_argument('--region', choices=REGION_IDS, help='Region ID (optional, default cn-north-4)')
    deploy_parser.add_argument('--non-interactive', action='store_true', help='Non-interactive mode, execute without confirmation')

    maas_parser = subparsers.add_parser('maas', help='Configure ModelArts large model on deployed Hermes instance')
    maas_parser.add_argument('--ak', required=True, help='Huawei Cloud AK (required)')
    maas_parser.add_argument('--sk', required=True, help='Huawei Cloud SK (required)')
    maas_parser.add_argument('--security-token', help='Security token for temporary credentials (optional)')
    maas_parser.add_argument('--resource-id', required=True, help='L Instance resource ID (required)')
    maas_parser.add_argument('--region-id', choices=REGION_IDS, help='Region ID (optional, default cn-north-4)')
    maas_parser.add_argument('--api-key', required=True, help='ModelArts API Key (required)')
    maas_parser.add_argument('--model-name', required=True, help='Large model name (required, e.g.: deepseek-v3.2, qwen-plus, glm-4)')
    maas_parser.add_argument('--api-base-url', default='https://api.modelarts-maas.com/v2', help='API Base URL (optional, default https://api.modelarts-maas.com/v2)')
    maas_parser.add_argument('--timeout', type=int, help='Timeout in seconds (optional, default 600)')
    maas_parser.add_argument('--execute-user', default='root', help='Execute user (optional, default root)')
    maas_parser.add_argument('--non-interactive', action='store_true', help='Non-interactive mode, execute without confirmation')

    channel_parser = subparsers.add_parser('channel', help='Configure bot channels on deployed Hermes instance')
    channel_parser.add_argument('--ak', required=True, help='Huawei Cloud AK (required)')
    channel_parser.add_argument('--sk', required=True, help='Huawei Cloud SK (required)')
    channel_parser.add_argument('--security-token', help='Security token for temporary credentials (optional)')
    channel_parser.add_argument('--resource-id', required=True, help='L Instance resource ID (required)')
    channel_parser.add_argument('--region-id', choices=REGION_IDS, help='Region ID (optional, default cn-north-4)')
    channel_parser.add_argument('--bot-platform', choices=['feishu', 'wecom'], required=True, help='Bot platform: feishu or wecom (required)')
    channel_parser.add_argument('--feishu-app-id', help='Feishu App ID (required when feishu platform is selected)')
    channel_parser.add_argument('--feishu-app-secret', help='Feishu App Secret (required when feishu platform is selected)')
    channel_parser.add_argument('--wecom-bot-id', help='WeCom Bot ID (required when wecom platform is selected)')
    channel_parser.add_argument('--wecom-secret', help='WeCom Secret (required when wecom platform is selected)')
    channel_parser.add_argument('--timeout', type=int, help='Timeout in seconds (optional, default 600)')
    channel_parser.add_argument('--execute-user', default='root', help='Execute user (optional, default root)')
    channel_parser.add_argument('--non-interactive', action='store_true', help='Non-interactive mode, execute without confirmation')

    gateway_parser = subparsers.add_parser('gateway', help='Restart Hermes Gateway')
    gateway_parser.add_argument('--ak', required=True, help='Huawei Cloud AK (required)')
    gateway_parser.add_argument('--sk', required=True, help='Huawei Cloud SK (required)')
    gateway_parser.add_argument('--security-token', help='Security token for temporary credentials (optional)')
    gateway_parser.add_argument('--resource-id', required=True, help='L Instance resource ID (required)')
    gateway_parser.add_argument('--region-id', choices=REGION_IDS, help='Region ID (optional, default cn-north-4)')
    gateway_parser.add_argument('--timeout', type=int, help='Timeout in seconds (optional, default 120)')
    gateway_parser.add_argument('--execute-user', default='root', help='Execute user (optional, default root)')
    gateway_parser.add_argument('--non-interactive', action='store_true', help='Non-interactive mode, execute without confirmation')

    query_parser = subparsers.add_parser('query', help='Query COC script execution result')
    query_parser.add_argument('--ak', required=True, help='Huawei Cloud AK (required)')
    query_parser.add_argument('--sk', required=True, help='Huawei Cloud SK (required)')
    query_parser.add_argument('--security-token', help='Security token for temporary credentials (optional)')
    query_parser.add_argument('--execute-uuid', required=True, help='Script execution UUID (e.g.: SCT2023083109562601af694bf)')

    args = parser.parse_args()

    try:
        if args.command == 'query':
            security_token = args.security_token if hasattr(args, 'security_token') else None
            print(f"Querying script execution result: {args.execute_uuid}")
            result = coc_query_execution(args.execute_uuid, args.ak, args.sk, security_token)
            data = result.get('data', {})
            if data:
                print("=" * 60)
                print("Query Result:")
                print("-" * 60)
                print(f"Batch Index: {data.get('batch_index', '')}")
                print(f"Total Instances: {data.get('total_instances', '')}")
                
                instances = data.get('execute_instances', [])
                if instances:
                    inst = instances[0]
                    print(f"Execution Status: {inst.get('status', '')}")
                    print(f"Instance ID: {inst.get('id', '')}")
                    print(f"Command UUID: {inst.get('cmd_uuid', '')}")
                    print(f"Execute Costs: {inst.get('execute_costs', '')}ms")
                    print("-" * 60)
                    if inst.get('message'):
                        print("Execution Output:")
                        print(inst['message'])
                    
                    target = inst.get('target_instance', {})
                    if target:
                        print("-" * 60)
                        print("Target Instance:")
                        print(f"  Resource ID: {target.get('resource_id', '')}")
                        print(f"  Region: {target.get('region_id', '')}")
                        print(f"  Provider: {target.get('provider', '')}")
                print("=" * 60)
            else:
                print(f"Query failed: {result.get('error', {}).get('message', 'Unknown error')}")
        elif args.command == 'maas':
            do_install_maas(args)
        elif args.command == 'channel':
            do_install_channel(args)
        elif args.command == 'gateway':
            do_restart_gateway(args)
        elif args.command == 'deploy':
            do_deploy_hermes(args)
        else:
            choice = show_main_menu()
            if choice == 0:
                print("退出程序")
                sys.exit(0)
            elif choice == 1:
                args.command = 'deploy'
                do_deploy_hermes(args)
            elif choice == 2:
                args.command = 'maas'
                do_install_maas(args)
            elif choice == 3:
                args.command = 'channel'
                do_install_channel(args)
            elif choice == 4:
                args.command = 'gateway'
                do_restart_gateway(args)
            elif choice == 5:
                ak = input("Please enter Huawei Cloud AK: ")
                sk = input("Please enter Huawei Cloud SK: ")
                execute_uuid = input("Please enter script execution UUID: ")
                print(f"Querying script execution result: {execute_uuid}")
                result = coc_query_execution(execute_uuid, ak, sk)
                data = result.get('data', {})
                if data:
                    print("=" * 60)
                    print("Query Result:")
                    print("-" * 60)
                    print(f"Batch Index: {data.get('batch_index', '')}")
                    print(f"Total Instances: {data.get('total_instances', '')}")
                    
                    instances = data.get('execute_instances', [])
                    if instances:
                        inst = instances[0]
                        print(f"Execution Status: {inst.get('status', '')}")
                        print(f"Instance ID: {inst.get('id', '')}")
                        print(f"Command UUID: {inst.get('cmd_uuid', '')}")
                        print(f"Execute Costs: {inst.get('execute_costs', '')}ms")
                        print("-" * 60)
                        if inst.get('message'):
                            print("Execution Output:")
                            print(inst['message'])
                        
                        target = inst.get('target_instance', {})
                        if target:
                            print("-" * 60)
                            print("Target Instance:")
                            print(f"  Resource ID: {target.get('resource_id', '')}")
                            print(f"  Region: {target.get('region_id', '')}")
                            print(f"  Provider: {target.get('provider', '')}")
                    print("=" * 60)
                else:
                    print(f"Query failed: {result.get('error', {}).get('message', 'Unknown error')}")
    except KeyboardInterrupt:
        print("\n\nUser interrupted operation")
        sys.exit(0)


if __name__ == '__main__':
    main()
