# -*- coding: utf-8 -*-
"""
Apache Doris SQL Keywords Definition
Source: Doris 3.1.4 Nereids ANTLR4 grammar
File: fe/fe-core/src/main/antlr4/org/apache/doris/nereids/DorisLexer.g4
Total keywords: 504 (between --DORIS-KEYWORD-LIST-START and --DORIS-KEYWORD-LIST-END)

Doris keyword classification:
- RESERVED: keywords NOT in the `nonReserved` rule of DorisParser.g4 cannot be
  used as bare identifiers. They must be backtick-quoted if used as identifiers.
- NON_RESERVED: keywords listed in the `nonReserved` rule can be used as bare
  identifiers without quoting.
"""

from enum import Enum


class KeywordCategory(Enum):
    RESERVED = "RESERVED_KEYWORD"
    NON_RESERVED = "NON_RESERVED_KEYWORD"


# Reserved keywords are those NOT in the `nonReserved` rule of DorisParser.g4.
# These are the SQL "hard" keywords: SELECT, FROM, WHERE, CREATE, INSERT, etc.
# Anything not in NON_RESERVED set below is considered RESERVED.
RESERVED_KEYWORD_NAMES = {
    # SQL core
    "select", "from", "where", "group", "order", "by", "having", "limit",
    "offset", "asc", "desc", "all", "distinct", "as", "and", "or", "not",
    "in", "is", "null", "true", "false", "like", "between", "case", "when",
    "then", "else", "end", "cast", "interval", "exists", "union", "intersect",
    "except", "minus", "join", "inner", "left", "right", "full", "cross",
    "outer", "natural", "on", "using", "with", "over", "partition",
    "distributed", "buckets", "engine", "properties", "hash", "random",
    "unique", "duplicate", "aggregate", "primary", "key", "index", "view",
    "materialized", "table", "tables", "database", "databases", "schema",
    "schemas", "function", "functions", "user", "role", "roles", "resource",
    "resources", "catalog", "catalogs", "load", "export", "backup", "restore",
    "kill", "begin", "commit", "rollback", "transaction", "explain", "desc",
    "describe", "create", "alter", "drop", "insert", "update", "delete",
    "into", "overwrite", "values", "value", "set", "sets", "show", "grant",
    "revoke", "privileges", "for", "to", "of", "add", "modify", "rename",
    "replace", "if", "exists", "default", "column", "columns", "comment",
    "references", "check", "constraint", "constraints", "foreign",
    # Doris-specific reserved
    "range", "list", "auto", "build", "deferred", "immediate", "complete",
    "manual", "schedule", "commit", "refresh", "pause", "resume", "cancel",
    "task", "tasks", "job", "jobs", "stage", "stages", "encryptkey",
    "encryptkeys", "policy", "vault", "vaults", "workload", "group", "groups",
    "repository", "repositories", "snapshot", "snapshots", "replica",
    "branch", "branches", "tag", "tags", "colocate", "sample", "out",
    "outfile", "format", "data", "file", "files", "rows", "percent",
    "repeatable", "unbounded", "preceding", "following", "current", "row",
    "rows", "range", "frame", "between", "extract", "position",
    # Operators as keywords
    "div", "mod", "rlike", "regexp",
    # Match operators
    "match", "match_all", "match_any", "match_phrase", "match_phrase_prefix",
    "match_phrase_edge", "match_regexp", "match_name", "match_name_glob",
    # Aggregate unions
    "hll_union", "bitmap_union", "quantile_union",
    # Misc reserved
    "account_lock", "account_unlock", "actions", "after", "against",
    "always", "analyze", "analyzed", "analyzer", "anti", "append", "array",
    "at", "authors", "backend", "backends", "backup", "belong", "bin",
    "binary", "binlog", "bitmap_empty", "brief", "broker", "builtin",
    "bulk", "cache", "cached", "call", "cancel", "chain", "char_filter",
    "clean", "cluster", "clusters", "collate", "collation", "collect",
    "column", "committed", "compact", "complete", "compute", "config",
    "connection", "connection_id", "consistent", "convert", "copy", "count",
    "creation", "cron", "demote", "demand", "diagnose", "diagnosis", "disk",
    "dynamic", "ends", "enter", "errors", "escape", "events", "every",
    "execute", "expired", "extended", "external", "failed_login_attempts",
    "fast", "feature", "fields", "filter", "free", "frontend", "frontends",
    "graph", "histogram", "hostname", "hotspot", "identified", "ignore",
    "immediate", "incremental", "indexes", "infile", "install", "instead",
    "isolation", "lateral", "less", "level", "lines", "link", "localtime",
    "localtimestamp", "lock", "logical", "manual", "migrate", "migrations",
    "mtmv", "name", "names", "negative", "never", "next", "no", "node",
    "non_nullable", "observer", "of", "offline", "online", "open",
    "optimized", "parsed", "password", "password_expire", "password_history",
    "password_lock_time", "password_reuse", "path", "period", "permissive",
    "physical", "plan", "play", "plugin", "plugins", "preceding", "prepare",
    "procedure", "processlist", "profile", "property", "query", "quota",
    "random", "recent", "recover", "recycle", "refresh", "replayer",
    "restrictive", "resume", "retain", "retention", "returns", "rewritten",
    "root", "rotate", "routine", "sample", "schedule", "scheduler", "session",
    "session_user", "shape", "signed", "skew", "soname", "split", "sql",
    "sql_block_rule", "start", "starts", "stats", "status", "stop", "storage",
    "stream", "streaming", "superuser", "switch", "sync", "system",
    "tablet", "tablets", "temporary", "terminated", "than", "time", "timestamp",
    "tokenizer", "token_filter", "transaction", "trash", "tree", "triggers",
    "trim", "truncate", "type", "types", "uncommitted", "uninstall", "union",
    "unique", "unlock", "unset", "unsigned", "up", "use", "user", "using",
    "variable", "variables", "variant", "verbose", "version", "view", "views",
    "warm", "warnings", "week", "whitelist", "work", "write", "xor", "year",
}


# ============================================================
# All 504 Doris keywords from DorisLexer.g4
# Format: (name_lower, token_name, category)
# ============================================================
KEYWORD_ENTRIES = [
    ("account_lock", "ACCOUNT_LOCK", KeywordCategory.RESERVED),
    ("account_unlock", "ACCOUNT_UNLOCK", KeywordCategory.RESERVED),
    ("actions", "ACTIONS", KeywordCategory.NON_RESERVED),
    ("add", "ADD", KeywordCategory.RESERVED),
    ("admin", "ADMIN", KeywordCategory.NON_RESERVED),
    ("after", "AFTER", KeywordCategory.NON_RESERVED),
    ("agg_state", "AGG_STATE", KeywordCategory.NON_RESERVED),
    ("aggregate", "AGGREGATE", KeywordCategory.RESERVED),
    ("alias", "ALIAS", KeywordCategory.NON_RESERVED),
    ("all", "ALL", KeywordCategory.RESERVED),
    ("alter", "ALTER", KeywordCategory.RESERVED),
    ("analyze", "ANALYZE", KeywordCategory.NON_RESERVED),
    ("analyzed", "ANALYZED", KeywordCategory.NON_RESERVED),
    ("analyzer", "ANALYZER", KeywordCategory.NON_RESERVED),
    ("and", "AND", KeywordCategory.RESERVED),
    ("anti", "ANTI", KeywordCategory.NON_RESERVED),
    ("append", "APPEND", KeywordCategory.NON_RESERVED),
    ("array", "ARRAY", KeywordCategory.NON_RESERVED),
    ("as", "AS", KeywordCategory.RESERVED),
    ("asc", "ASC", KeywordCategory.RESERVED),
    ("at", "AT", KeywordCategory.NON_RESERVED),
    ("authors", "AUTHORS", KeywordCategory.NON_RESERVED),
    ("auto", "AUTO", KeywordCategory.NON_RESERVED),
    ("auto_increment", "AUTO_INCREMENT", KeywordCategory.NON_RESERVED),
    ("always", "ALWAYS", KeywordCategory.NON_RESERVED),
    ("backend", "BACKEND", KeywordCategory.NON_RESERVED),
    ("backends", "BACKENDS", KeywordCategory.NON_RESERVED),
    ("backup", "BACKUP", KeywordCategory.RESERVED),
    ("begin", "BEGIN", KeywordCategory.RESERVED),
    ("belong", "BELONG", KeywordCategory.NON_RESERVED),
    ("between", "BETWEEN", KeywordCategory.RESERVED),
    ("bigint", "BIGINT", KeywordCategory.NON_RESERVED),
    ("bin", "BIN", KeywordCategory.NON_RESERVED),
    ("binary", "BINARY", KeywordCategory.NON_RESERVED),
    ("binlog", "BINLOG", KeywordCategory.NON_RESERVED),
    ("bitand", "BITAND", KeywordCategory.NON_RESERVED),
    ("bitmap", "BITMAP", KeywordCategory.NON_RESERVED),
    ("bitmap_empty", "BITMAP_EMPTY", KeywordCategory.NON_RESERVED),
    ("bitmap_union", "BITMAP_UNION", KeywordCategory.NON_RESERVED),
    ("bitor", "BITOR", KeywordCategory.NON_RESERVED),
    ("bitxor", "BITXOR", KeywordCategory.NON_RESERVED),
    ("blob", "BLOB", KeywordCategory.NON_RESERVED),
    ("boolean", "BOOLEAN", KeywordCategory.NON_RESERVED),
    ("branch", "BRANCH", KeywordCategory.NON_RESERVED),
    ("brief", "BRIEF", KeywordCategory.NON_RESERVED),
    ("broker", "BROKER", KeywordCategory.NON_RESERVED),
    ("buckets", "BUCKETS", KeywordCategory.RESERVED),
    ("build", "BUILD", KeywordCategory.NON_RESERVED),
    ("builtin", "BUILTIN", KeywordCategory.NON_RESERVED),
    ("bulk", "BULK", KeywordCategory.NON_RESERVED),
    ("by", "BY", KeywordCategory.RESERVED),
    ("cache", "CACHE", KeywordCategory.NON_RESERVED),
    ("cached", "CACHED", KeywordCategory.NON_RESERVED),
    ("call", "CALL", KeywordCategory.NON_RESERVED),
    ("cancel", "CANCEL", KeywordCategory.RESERVED),
    ("case", "CASE", KeywordCategory.RESERVED),
    ("cast", "CAST", KeywordCategory.RESERVED),
    ("catalog", "CATALOG", KeywordCategory.NON_RESERVED),
    ("catalogs", "CATALOGS", KeywordCategory.NON_RESERVED),
    ("chain", "CHAIN", KeywordCategory.NON_RESERVED),
    ("char", "CHAR", KeywordCategory.NON_RESERVED),
    ("character", "CHAR", KeywordCategory.NON_RESERVED),
    ("charset", "CHARSET", KeywordCategory.NON_RESERVED),
    ("char_filter", "CHAR_FILTER", KeywordCategory.NON_RESERVED),
    ("check", "CHECK", KeywordCategory.RESERVED),
    ("clean", "CLEAN", KeywordCategory.NON_RESERVED),
    ("cluster", "CLUSTER", KeywordCategory.NON_RESERVED),
    ("clusters", "CLUSTERS", KeywordCategory.NON_RESERVED),
    ("collate", "COLLATE", KeywordCategory.NON_RESERVED),
    ("collation", "COLLATION", KeywordCategory.NON_RESERVED),
    ("collect", "COLLECT", KeywordCategory.NON_RESERVED),
    ("colocate", "COLOCATE", KeywordCategory.NON_RESERVED),
    ("column", "COLUMN", KeywordCategory.RESERVED),
    ("columns", "COLUMNS", KeywordCategory.NON_RESERVED),
    ("comment", "COMMENT", KeywordCategory.NON_RESERVED),
    ("commit", "COMMIT", KeywordCategory.RESERVED),
    ("committed", "COMMITTED", KeywordCategory.NON_RESERVED),
    ("compact", "COMPACT", KeywordCategory.NON_RESERVED),
    ("complete", "COMPLETE", KeywordCategory.NON_RESERVED),
    ("compress_type", "COMPRESS_TYPE", KeywordCategory.NON_RESERVED),
    ("compute", "COMPUTE", KeywordCategory.NON_RESERVED),
    ("conditions", "CONDITIONS", KeywordCategory.NON_RESERVED),
    ("config", "CONFIG", KeywordCategory.NON_RESERVED),
    ("connection", "CONNECTION", KeywordCategory.NON_RESERVED),
    ("connection_id", "CONNECTION_ID", KeywordCategory.NON_RESERVED),
    ("consistent", "CONSISTENT", KeywordCategory.NON_RESERVED),
    ("constraint", "CONSTRAINT", KeywordCategory.RESERVED),
    ("constraints", "CONSTRAINTS", KeywordCategory.NON_RESERVED),
    ("convert", "CONVERT", KeywordCategory.NON_RESERVED),
    ("convert_lsc", "CONVERT_LSC", KeywordCategory.NON_RESERVED),
    ("copy", "COPY", KeywordCategory.NON_RESERVED),
    ("count", "COUNT", KeywordCategory.NON_RESERVED),
    ("create", "CREATE", KeywordCategory.RESERVED),
    ("creation", "CREATION", KeywordCategory.NON_RESERVED),
    ("cron", "CRON", KeywordCategory.NON_RESERVED),
    ("cross", "CROSS", KeywordCategory.RESERVED),
    ("cube", "CUBE", KeywordCategory.NON_RESERVED),
    ("current", "CURRENT", KeywordCategory.NON_RESERVED),
    ("current_catalog", "CURRENT_CATALOG", KeywordCategory.NON_RESERVED),
    ("current_date", "CURRENT_DATE", KeywordCategory.NON_RESERVED),
    ("current_time", "CURRENT_TIME", KeywordCategory.NON_RESERVED),
    ("current_timestamp", "CURRENT_TIMESTAMP", KeywordCategory.NON_RESERVED),
    ("current_user", "CURRENT_USER", KeywordCategory.NON_RESERVED),
    ("data", "DATA", KeywordCategory.RESERVED),
    ("database", "DATABASE", KeywordCategory.NON_RESERVED),
    ("databases", "DATABASES", KeywordCategory.NON_RESERVED),
    ("date", "DATE", KeywordCategory.NON_RESERVED),
    ("datetime", "DATETIME", KeywordCategory.NON_RESERVED),
    ("datetimev2", "DATETIMEV2", KeywordCategory.NON_RESERVED),
    ("datev2", "DATEV2", KeywordCategory.NON_RESERVED),
    ("datetimev1", "DATETIMEV1", KeywordCategory.NON_RESERVED),
    ("datev1", "DATEV1", KeywordCategory.NON_RESERVED),
    ("day", "DAY", KeywordCategory.NON_RESERVED),
    ("days", "DAYS", KeywordCategory.NON_RESERVED),
    ("decimal", "DECIMAL", KeywordCategory.NON_RESERVED),
    ("decimalv2", "DECIMALV2", KeywordCategory.NON_RESERVED),
    ("decimalv3", "DECIMALV3", KeywordCategory.NON_RESERVED),
    ("decommission", "DECOMMISSION", KeywordCategory.NON_RESERVED),
    ("default", "DEFAULT", KeywordCategory.RESERVED),
    ("deferred", "DEFERRED", KeywordCategory.NON_RESERVED),
    ("delete", "DELETE", KeywordCategory.RESERVED),
    ("demand", "DEMAND", KeywordCategory.NON_RESERVED),
    ("desc", "DESC", KeywordCategory.RESERVED),
    ("describe", "DESCRIBE", KeywordCategory.RESERVED),
    ("diagnose", "DIAGNOSE", KeywordCategory.NON_RESERVED),
    ("diagnosis", "DIAGNOSIS", KeywordCategory.NON_RESERVED),
    ("disk", "DISK", KeywordCategory.NON_RESERVED),
    ("distinct", "DISTINCT", KeywordCategory.RESERVED),
    ("distinctpc", "DISTINCTPC", KeywordCategory.NON_RESERVED),
    ("distinctpcsa", "DISTINCTPCSA", KeywordCategory.NON_RESERVED),
    ("distributed", "DISTRIBUTED", KeywordCategory.RESERVED),
    ("distribution", "DISTRIBUTION", KeywordCategory.NON_RESERVED),
    ("div", "DIV", KeywordCategory.RESERVED),
    ("do", "DO", KeywordCategory.NON_RESERVED),
    ("doris_internal_table_id", "DORIS_INTERNAL_TABLE_ID", KeywordCategory.NON_RESERVED),
    ("double", "DOUBLE", KeywordCategory.NON_RESERVED),
    ("drop", "DROP", KeywordCategory.RESERVED),
    ("dropp", "DROPP", KeywordCategory.NON_RESERVED),
    ("dual", "DUAL", KeywordCategory.NON_RESERVED),
    ("dump", "DUMP", KeywordCategory.NON_RESERVED),
    ("duplicate", "DUPLICATE", KeywordCategory.RESERVED),
    ("dynamic", "DYNAMIC", KeywordCategory.NON_RESERVED),
    ("e", "E", KeywordCategory.NON_RESERVED),
    ("else", "ELSE", KeywordCategory.RESERVED),
    ("enable", "ENABLE", KeywordCategory.NON_RESERVED),
    ("encryption", "ENCRYPTION", KeywordCategory.NON_RESERVED),
    ("encryptkey", "ENCRYPTKEY", KeywordCategory.RESERVED),
    ("encryptkeys", "ENCRYPTKEYS", KeywordCategory.NON_RESERVED),
    ("end", "END", KeywordCategory.RESERVED),
    ("ends", "ENDS", KeywordCategory.NON_RESERVED),
    ("engine", "ENGINE", KeywordCategory.RESERVED),
    ("engines", "ENGINES", KeywordCategory.NON_RESERVED),
    ("enter", "ENTER", KeywordCategory.NON_RESERVED),
    ("errors", "ERRORS", KeywordCategory.NON_RESERVED),
    ("escape", "ESCAPE", KeywordCategory.NON_RESERVED),
    ("events", "EVENTS", KeywordCategory.NON_RESERVED),
    ("every", "EVERY", KeywordCategory.NON_RESERVED),
    ("except", "EXCEPT", KeywordCategory.RESERVED),
    ("exclude", "EXCLUDE", KeywordCategory.NON_RESERVED),
    ("execute", "EXECUTE", KeywordCategory.NON_RESERVED),
    ("exists", "EXISTS", KeywordCategory.RESERVED),
    ("expired", "EXPIRED", KeywordCategory.NON_RESERVED),
    ("explain", "EXPLAIN", KeywordCategory.RESERVED),
    ("export", "EXPORT", KeywordCategory.RESERVED),
    ("extended", "EXTENDED", KeywordCategory.NON_RESERVED),
    ("external", "EXTERNAL", KeywordCategory.NON_RESERVED),
    ("extract", "EXTRACT", KeywordCategory.RESERVED),
    ("failed_login_attempts", "FAILED_LOGIN_ATTEMPTS", KeywordCategory.NON_RESERVED),
    ("false", "FALSE", KeywordCategory.RESERVED),
    ("fast", "FAST", KeywordCategory.NON_RESERVED),
    ("feature", "FEATURE", KeywordCategory.NON_RESERVED),
    ("fields", "FIELDS", KeywordCategory.NON_RESERVED),
    ("file", "FILE", KeywordCategory.NON_RESERVED),
    ("filter", "FILTER", KeywordCategory.NON_RESERVED),
    ("first", "FIRST", KeywordCategory.NON_RESERVED),
    ("float", "FLOAT", KeywordCategory.NON_RESERVED),
    ("follower", "FOLLOWER", KeywordCategory.NON_RESERVED),
    ("following", "FOLLOWING", KeywordCategory.NON_RESERVED),
    ("for", "FOR", KeywordCategory.RESERVED),
    ("foreign", "FOREIGN", KeywordCategory.RESERVED),
    ("force", "FORCE", KeywordCategory.NON_RESERVED),
    ("format", "FORMAT", KeywordCategory.NON_RESERVED),
    ("free", "FREE", KeywordCategory.NON_RESERVED),
    ("from", "FROM", KeywordCategory.RESERVED),
    ("frontend", "FRONTEND", KeywordCategory.NON_RESERVED),
    ("frontends", "FRONTENDS", KeywordCategory.NON_RESERVED),
    ("full", "FULL", KeywordCategory.RESERVED),
    ("function", "FUNCTION", KeywordCategory.NON_RESERVED),
    ("functions", "FUNCTIONS", KeywordCategory.NON_RESERVED),
    ("generated", "GENERATED", KeywordCategory.NON_RESERVED),
    ("generic", "GENERIC", KeywordCategory.NON_RESERVED),
    ("global", "GLOBAL", KeywordCategory.NON_RESERVED),
    ("grant", "GRANT", KeywordCategory.RESERVED),
    ("grants", "GRANTS", KeywordCategory.NON_RESERVED),
    ("graph", "GRAPH", KeywordCategory.NON_RESERVED),
    ("group", "GROUP", KeywordCategory.RESERVED),
    ("grouping", "GROUPING", KeywordCategory.NON_RESERVED),
    ("groups", "GROUPS", KeywordCategory.NON_RESERVED),
    ("hash", "HASH", KeywordCategory.RESERVED),
    ("having", "HAVING", KeywordCategory.RESERVED),
    ("hdfs", "HDFS", KeywordCategory.NON_RESERVED),
    ("help", "HELP", KeywordCategory.NON_RESERVED),
    ("histogram", "HISTOGRAM", KeywordCategory.NON_RESERVED),
    ("hll", "HLL", KeywordCategory.NON_RESERVED),
    ("hll_union", "HLL_UNION", KeywordCategory.NON_RESERVED),
    ("hostname", "HOSTNAME", KeywordCategory.NON_RESERVED),
    ("hotspot", "HOTSPOT", KeywordCategory.NON_RESERVED),
    ("hour", "HOUR", KeywordCategory.NON_RESERVED),
    ("hours", "HOURS", KeywordCategory.NON_RESERVED),
    ("hub", "HUB", KeywordCategory.NON_RESERVED),
    ("identified", "IDENTIFIED", KeywordCategory.NON_RESERVED),
    ("if", "IF", KeywordCategory.RESERVED),
    ("ignore", "IGNORE", KeywordCategory.NON_RESERVED),
    ("immediate", "IMMEDIATE", KeywordCategory.NON_RESERVED),
    ("in", "IN", KeywordCategory.RESERVED),
    ("incremental", "INCREMENTAL", KeywordCategory.NON_RESERVED),
    ("index", "INDEX", KeywordCategory.RESERVED),
    ("indexes", "INDEXES", KeywordCategory.NON_RESERVED),
    ("infile", "INFILE", KeywordCategory.NON_RESERVED),
    ("inner", "INNER", KeywordCategory.RESERVED),
    ("insert", "INSERT", KeywordCategory.RESERVED),
    ("install", "INSTALL", KeywordCategory.NON_RESERVED),
    ("int", "INT", KeywordCategory.NON_RESERVED),
    ("integer", "INTEGER", KeywordCategory.NON_RESERVED),
    ("intermediate", "INTERMEDIATE", KeywordCategory.NON_RESERVED),
    ("intersect", "INTERSECT", KeywordCategory.RESERVED),
    ("interval", "INTERVAL", KeywordCategory.RESERVED),
    ("into", "INTO", KeywordCategory.RESERVED),
    ("inverted", "INVERTED", KeywordCategory.NON_RESERVED),
    ("ipv4", "IPV4", KeywordCategory.NON_RESERVED),
    ("ipv6", "IPV6", KeywordCategory.NON_RESERVED),
    ("is", "IS", KeywordCategory.RESERVED),
    ("is_not_null_pred", "IS_NOT_NULL_PRED", KeywordCategory.NON_RESERVED),
    ("is_null_pred", "IS_NULL_PRED", KeywordCategory.NON_RESERVED),
    ("isnull", "ISNULL", KeywordCategory.NON_RESERVED),
    ("isolation", "ISOLATION", KeywordCategory.NON_RESERVED),
    ("job", "JOB", KeywordCategory.RESERVED),
    ("jobs", "JOBS", KeywordCategory.NON_RESERVED),
    ("join", "JOIN", KeywordCategory.RESERVED),
    ("json", "JSON", KeywordCategory.NON_RESERVED),
    ("jsonb", "JSONB", KeywordCategory.NON_RESERVED),
    ("key", "KEY", KeywordCategory.RESERVED),
    ("keys", "KEYS", KeywordCategory.NON_RESERVED),
    ("kill", "KILL", KeywordCategory.RESERVED),
    ("label", "LABEL", KeywordCategory.NON_RESERVED),
    ("largeint", "LARGEINT", KeywordCategory.NON_RESERVED),
    ("last", "LAST", KeywordCategory.NON_RESERVED),
    ("lateral", "LATERAL", KeywordCategory.RESERVED),
    ("ldap", "LDAP", KeywordCategory.NON_RESERVED),
    ("ldap_admin_password", "LDAP_ADMIN_PASSWORD", KeywordCategory.NON_RESERVED),
    ("left", "LEFT", KeywordCategory.RESERVED),
    ("less", "LESS", KeywordCategory.NON_RESERVED),
    ("level", "LEVEL", KeywordCategory.NON_RESERVED),
    ("like", "LIKE", KeywordCategory.RESERVED),
    ("limit", "LIMIT", KeywordCategory.RESERVED),
    ("lines", "LINES", KeywordCategory.NON_RESERVED),
    ("link", "LINK", KeywordCategory.NON_RESERVED),
    ("list", "LIST", KeywordCategory.RESERVED),
    ("load", "LOAD", KeywordCategory.RESERVED),
    ("local", "LOCAL", KeywordCategory.NON_RESERVED),
    ("localtime", "LOCALTIME", KeywordCategory.RESERVED),
    ("localtimestamp", "LOCALTIMESTAMP", KeywordCategory.RESERVED),
    ("location", "LOCATION", KeywordCategory.NON_RESERVED),
    ("lock", "LOCK", KeywordCategory.NON_RESERVED),
    ("logical", "LOGICAL", KeywordCategory.NON_RESERVED),
    ("low_priority", "LOW_PRIORITY", KeywordCategory.NON_RESERVED),
    ("manual", "MANUAL", KeywordCategory.NON_RESERVED),
    ("map", "MAP", KeywordCategory.NON_RESERVED),
    ("match", "MATCH", KeywordCategory.NON_RESERVED),
    ("match_all", "MATCH_ALL", KeywordCategory.RESERVED),
    ("match_any", "MATCH_ANY", KeywordCategory.RESERVED),
    ("match_phrase", "MATCH_PHRASE", KeywordCategory.RESERVED),
    ("match_phrase_edge", "MATCH_PHRASE_EDGE", KeywordCategory.RESERVED),
    ("match_phrase_prefix", "MATCH_PHRASE_PREFIX", KeywordCategory.RESERVED),
    ("match_regexp", "MATCH_REGEXP", KeywordCategory.RESERVED),
    ("match_name", "MATCH_NAME", KeywordCategory.NON_RESERVED),
    ("match_name_glob", "MATCH_NAME_GLOB", KeywordCategory.NON_RESERVED),
    ("materialized", "MATERIALIZED", KeywordCategory.RESERVED),
    ("max", "MAX", KeywordCategory.NON_RESERVED),
    ("maxvalue", "MAXVALUE", KeywordCategory.NON_RESERVED),
    ("memo", "MEMO", KeywordCategory.NON_RESERVED),
    ("merge", "MERGE", KeywordCategory.NON_RESERVED),
    ("migrate", "MIGRATE", KeywordCategory.NON_RESERVED),
    ("migrations", "MIGRATIONS", KeywordCategory.NON_RESERVED),
    ("min", "MIN", KeywordCategory.NON_RESERVED),
    ("minus", "MINUS", KeywordCategory.RESERVED),
    ("minute", "MINUTE", KeywordCategory.NON_RESERVED),
    ("minutes", "MINUTES", KeywordCategory.NON_RESERVED),
    ("modify", "MODIFY", KeywordCategory.RESERVED),
    ("month", "MONTH", KeywordCategory.NON_RESERVED),
    ("mtmv", "MTMV", KeywordCategory.NON_RESERVED),
    ("name", "NAME", KeywordCategory.NON_RESERVED),
    ("names", "NAMES", KeywordCategory.NON_RESERVED),
    ("natural", "NATURAL", KeywordCategory.RESERVED),
    ("negative", "NEGATIVE", KeywordCategory.NON_RESERVED),
    ("never", "NEVER", KeywordCategory.NON_RESERVED),
    ("next", "NEXT", KeywordCategory.NON_RESERVED),
    ("ngram_bf", "NGRAM_BF", KeywordCategory.NON_RESERVED),
    ("no", "NO", KeywordCategory.NON_RESERVED),
    ("non_nullable", "NON_NULLABLE", KeywordCategory.NON_RESERVED),
    ("not", "NOT", KeywordCategory.RESERVED),
    ("null", "NULL", KeywordCategory.RESERVED),
    ("nulls", "NULLS", KeywordCategory.NON_RESERVED),
    ("observer", "OBSERVER", KeywordCategory.NON_RESERVED),
    ("of", "OF", KeywordCategory.RESERVED),
    ("offset", "OFFSET", KeywordCategory.RESERVED),
    ("on", "ON", KeywordCategory.RESERVED),
    ("only", "ONLY", KeywordCategory.NON_RESERVED),
    ("open", "OPEN", KeywordCategory.NON_RESERVED),
    ("optimized", "OPTIMIZED", KeywordCategory.NON_RESERVED),
    ("or", "OR", KeywordCategory.RESERVED),
    ("order", "ORDER", KeywordCategory.RESERVED),
    ("outer", "OUTER", KeywordCategory.RESERVED),
    ("outfile", "OUTFILE", KeywordCategory.RESERVED),
    ("over", "OVER", KeywordCategory.RESERVED),
    ("overwrite", "OVERWRITE", KeywordCategory.RESERVED),
    ("parameter", "PARAMETER", KeywordCategory.NON_RESERVED),
    ("parsed", "PARSED", KeywordCategory.NON_RESERVED),
    ("partition", "PARTITION", KeywordCategory.RESERVED),
    ("partitions", "PARTITIONS", KeywordCategory.NON_RESERVED),
    ("password", "PASSWORD", KeywordCategory.NON_RESERVED),
    ("password_expire", "PASSWORD_EXPIRE", KeywordCategory.NON_RESERVED),
    ("password_history", "PASSWORD_HISTORY", KeywordCategory.NON_RESERVED),
    ("password_lock_time", "PASSWORD_LOCK_TIME", KeywordCategory.NON_RESERVED),
    ("password_reuse", "PASSWORD_REUSE", KeywordCategory.NON_RESERVED),
    ("path", "PATH", KeywordCategory.NON_RESERVED),
    ("pause", "PAUSE", KeywordCategory.NON_RESERVED),
    ("percent", "PERCENT", KeywordCategory.NON_RESERVED),
    ("period", "PERIOD", KeywordCategory.NON_RESERVED),
    ("permissive", "PERMISSIVE", KeywordCategory.NON_RESERVED),
    ("physical", "PHYSICAL", KeywordCategory.NON_RESERVED),
    ("pi", "PI", KeywordCategory.NON_RESERVED),
    ("placeholder", "PLACEHOLDER", KeywordCategory.NON_RESERVED),
    ("plan", "PLAN", KeywordCategory.NON_RESERVED),
    ("play", "PLAY", KeywordCategory.NON_RESERVED),
    ("privileges", "PRIVILEGES", KeywordCategory.RESERVED),
    ("process", "PROCESS", KeywordCategory.NON_RESERVED),
    ("plugin", "PLUGIN", KeywordCategory.NON_RESERVED),
    ("plugins", "PLUGINS", KeywordCategory.NON_RESERVED),
    ("policy", "POLICY", KeywordCategory.RESERVED),
    ("preceding", "PRECEDING", KeywordCategory.NON_RESERVED),
    ("prepare", "PREPARE", KeywordCategory.NON_RESERVED),
    ("primary", "PRIMARY", KeywordCategory.RESERVED),
    ("proc", "PROC", KeywordCategory.NON_RESERVED),
    ("procedure", "PROCEDURE", KeywordCategory.NON_RESERVED),
    ("processlist", "PROCESSLIST", KeywordCategory.NON_RESERVED),
    ("profile", "PROFILE", KeywordCategory.NON_RESERVED),
    ("properties", "PROPERTIES", KeywordCategory.RESERVED),
    ("property", "PROPERTY", KeywordCategory.NON_RESERVED),
    ("quantile_state", "QUANTILE_STATE", KeywordCategory.NON_RESERVED),
    ("quantile_union", "QUANTILE_UNION", KeywordCategory.NON_RESERVED),
    ("query", "QUERY", KeywordCategory.NON_RESERVED),
    ("quota", "QUOTA", KeywordCategory.NON_RESERVED),
    ("random", "RANDOM", KeywordCategory.RESERVED),
    ("range", "RANGE", KeywordCategory.RESERVED),
    ("read", "READ", KeywordCategory.NON_RESERVED),
    ("real", "REAL", KeywordCategory.NON_RESERVED),
    ("rebalance", "REBALANCE", KeywordCategory.NON_RESERVED),
    ("recent", "RECENT", KeywordCategory.NON_RESERVED),
    ("recover", "RECOVER", KeywordCategory.NON_RESERVED),
    ("recycle", "RECYCLE", KeywordCategory.NON_RESERVED),
    ("refresh", "REFRESH", KeywordCategory.NON_RESERVED),
    ("references", "REFERENCES", KeywordCategory.RESERVED),
    ("regexp", "REGEXP", KeywordCategory.RESERVED),
    ("release", "RELEASE", KeywordCategory.NON_RESERVED),
    ("rename", "RENAME", KeywordCategory.RESERVED),
    ("repair", "REPAIR", KeywordCategory.NON_RESERVED),
    ("repeatable", "REPEATABLE", KeywordCategory.NON_RESERVED),
    ("replace", "REPLACE", KeywordCategory.RESERVED),
    ("replace_if_not_null", "REPLACE_IF_NOT_NULL", KeywordCategory.NON_RESERVED),
    ("replayer", "REPLAYER", KeywordCategory.NON_RESERVED),
    ("replica", "REPLICA", KeywordCategory.NON_RESERVED),
    ("repositories", "REPOSITORIES", KeywordCategory.NON_RESERVED),
    ("repository", "REPOSITORY", KeywordCategory.NON_RESERVED),
    ("resource", "RESOURCE", KeywordCategory.NON_RESERVED),
    ("resources", "RESOURCES", KeywordCategory.NON_RESERVED),
    ("restore", "RESTORE", KeywordCategory.RESERVED),
    ("restrictive", "RESTRICTIVE", KeywordCategory.NON_RESERVED),
    ("resume", "RESUME", KeywordCategory.NON_RESERVED),
    ("retain", "RETAIN", KeywordCategory.NON_RESERVED),
    ("retention", "RETENTION", KeywordCategory.NON_RESERVED),
    ("returns", "RETURNS", KeywordCategory.NON_RESERVED),
    ("revoke", "REVOKE", KeywordCategory.RESERVED),
    ("rewritten", "REWRITTEN", KeywordCategory.NON_RESERVED),
    ("right", "RIGHT", KeywordCategory.RESERVED),
    ("rlike", "RLIKE", KeywordCategory.RESERVED),
    ("role", "ROLE", KeywordCategory.NON_RESERVED),
    ("roles", "ROLES", KeywordCategory.NON_RESERVED),
    ("rollback", "ROLLBACK", KeywordCategory.RESERVED),
    ("rollup", "ROLLUP", KeywordCategory.NON_RESERVED),
    ("root", "ROOT", KeywordCategory.NON_RESERVED),
    ("rotate", "ROTATE", KeywordCategory.NON_RESERVED),
    ("routine", "ROUTINE", KeywordCategory.NON_RESERVED),
    ("row", "ROW", KeywordCategory.NON_RESERVED),
    ("rows", "ROWS", KeywordCategory.RESERVED),
    ("s3", "S3", KeywordCategory.NON_RESERVED),
    ("sample", "SAMPLE", KeywordCategory.RESERVED),
    ("schedule", "SCHEDULE", KeywordCategory.NON_RESERVED),
    ("scheduler", "SCHEDULER", KeywordCategory.NON_RESERVED),
    ("schema", "SCHEMA", KeywordCategory.NON_RESERVED),
    ("schemas", "SCHEMAS", KeywordCategory.NON_RESERVED),
    ("second", "SECOND", KeywordCategory.NON_RESERVED),
    ("select", "SELECT", KeywordCategory.RESERVED),
    ("semi", "SEMI", KeywordCategory.NON_RESERVED),
    ("serializable", "SERIALIZABLE", KeywordCategory.NON_RESERVED),
    ("session", "SESSION", KeywordCategory.NON_RESERVED),
    ("session_user", "SESSION_USER", KeywordCategory.NON_RESERVED),
    ("set", "SET", KeywordCategory.RESERVED),
    ("sets", "SETS", KeywordCategory.NON_RESERVED),
    ("set_session_variable", "SET_SESSION_VARIABLE", KeywordCategory.NON_RESERVED),
    ("shape", "SHAPE", KeywordCategory.NON_RESERVED),
    ("show", "SHOW", KeywordCategory.RESERVED),
    ("signed", "SIGNED", KeywordCategory.NON_RESERVED),
    ("skew", "SKEW", KeywordCategory.NON_RESERVED),
    ("smallint", "SMALLINT", KeywordCategory.NON_RESERVED),
    ("snapshot", "SNAPSHOT", KeywordCategory.NON_RESERVED),
    ("snapshots", "SNAPSHOTS", KeywordCategory.NON_RESERVED),
    ("soname", "SONAME", KeywordCategory.NON_RESERVED),
    ("split", "SPLIT", KeywordCategory.NON_RESERVED),
    ("sql", "SQL", KeywordCategory.NON_RESERVED),
    ("sql_block_rule", "SQL_BLOCK_RULE", KeywordCategory.RESERVED),
    ("stage", "STAGE", KeywordCategory.RESERVED),
    ("stages", "STAGES", KeywordCategory.NON_RESERVED),
    ("start", "START", KeywordCategory.NON_RESERVED),
    ("starts", "STARTS", KeywordCategory.NON_RESERVED),
    ("stats", "STATS", KeywordCategory.NON_RESERVED),
    ("status", "STATUS", KeywordCategory.NON_RESERVED),
    ("stop", "STOP", KeywordCategory.NON_RESERVED),
    ("storage", "STORAGE", KeywordCategory.NON_RESERVED),
    ("stream", "STREAM", KeywordCategory.NON_RESERVED),
    ("streaming", "STREAMING", KeywordCategory.NON_RESERVED),
    ("string", "STRING", KeywordCategory.NON_RESERVED),
    ("struct", "STRUCT", KeywordCategory.NON_RESERVED),
    ("sum", "SUM", KeywordCategory.NON_RESERVED),
    ("superuser", "SUPERUSER", KeywordCategory.NON_RESERVED),
    ("switch", "SWITCH", KeywordCategory.NON_RESERVED),
    ("sync", "SYNC", KeywordCategory.NON_RESERVED),
    ("system", "SYSTEM", KeywordCategory.NON_RESERVED),
    ("table", "TABLE", KeywordCategory.RESERVED),
    ("tables", "TABLES", KeywordCategory.NON_RESERVED),
    ("tablesample", "TABLESAMPLE", KeywordCategory.RESERVED),
    ("tablet", "TABLET", KeywordCategory.NON_RESERVED),
    ("tablets", "TABLETS", KeywordCategory.NON_RESERVED),
    ("tag", "TAG", KeywordCategory.NON_RESERVED),
    ("task", "TASK", KeywordCategory.NON_RESERVED),
    ("tasks", "TASKS", KeywordCategory.NON_RESERVED),
    ("tde", "TDE", KeywordCategory.NON_RESERVED),
    ("temporary", "TEMPORARY", KeywordCategory.NON_RESERVED),
    ("terminated", "TERMINATED", KeywordCategory.NON_RESERVED),
    ("text", "TEXT", KeywordCategory.NON_RESERVED),
    ("than", "THAN", KeywordCategory.NON_RESERVED),
    ("then", "THEN", KeywordCategory.RESERVED),
    ("time", "TIME", KeywordCategory.NON_RESERVED),
    ("timestamp", "TIMESTAMP", KeywordCategory.NON_RESERVED),
    ("tinyint", "TINYINT", KeywordCategory.NON_RESERVED),
    ("to", "TO", KeywordCategory.RESERVED),
    ("tokenizer", "TOKENIZER", KeywordCategory.NON_RESERVED),
    ("token_filter", "TOKEN_FILTER", KeywordCategory.NON_RESERVED),
    ("transaction", "TRANSACTION", KeywordCategory.RESERVED),
    ("trash", "TRASH", KeywordCategory.NON_RESERVED),
    ("tree", "TREE", KeywordCategory.NON_RESERVED),
    ("triggers", "TRIGGERS", KeywordCategory.NON_RESERVED),
    ("trim", "TRIM", KeywordCategory.NON_RESERVED),
    ("true", "TRUE", KeywordCategory.RESERVED),
    ("truncate", "TRUNCATE", KeywordCategory.NON_RESERVED),
    ("type", "TYPE", KeywordCategory.NON_RESERVED),
    ("type_cast", "TYPECAST", KeywordCategory.NON_RESERVED),
    ("types", "TYPES", KeywordCategory.NON_RESERVED),
    ("unbounded", "UNBOUNDED", KeywordCategory.NON_RESERVED),
    ("uncommitted", "UNCOMMITTED", KeywordCategory.NON_RESERVED),
    ("uninstall", "UNINSTALL", KeywordCategory.NON_RESERVED),
    ("union", "UNION", KeywordCategory.RESERVED),
    ("unique", "UNIQUE", KeywordCategory.RESERVED),
    ("unlock", "UNLOCK", KeywordCategory.NON_RESERVED),
    ("unset", "UNSET", KeywordCategory.NON_RESERVED),
    ("unsigned", "UNSIGNED", KeywordCategory.NON_RESERVED),
    ("up", "UP", KeywordCategory.NON_RESERVED),
    ("update", "UPDATE", KeywordCategory.RESERVED),
    ("use", "USE", KeywordCategory.NON_RESERVED),
    ("user", "USER", KeywordCategory.NON_RESERVED),
    ("using", "USING", KeywordCategory.RESERVED),
    ("value", "VALUE", KeywordCategory.NON_RESERVED),
    ("values", "VALUES", KeywordCategory.RESERVED),
    ("varchar", "VARCHAR", KeywordCategory.NON_RESERVED),
    ("variable", "VARIABLE", KeywordCategory.NON_RESERVED),
    ("variables", "VARIABLES", KeywordCategory.NON_RESERVED),
    ("variant", "VARIANT", KeywordCategory.NON_RESERVED),
    ("vault", "VAULT", KeywordCategory.NON_RESERVED),
    ("vaults", "VAULTS", KeywordCategory.NON_RESERVED),
    ("verbose", "VERBOSE", KeywordCategory.NON_RESERVED),
    ("version", "VERSION", KeywordCategory.NON_RESERVED),
    ("view", "VIEW", KeywordCategory.RESERVED),
    ("views", "VIEWS", KeywordCategory.NON_RESERVED),
    ("warm", "WARM", KeywordCategory.NON_RESERVED),
    ("warnings", "WARNINGS", KeywordCategory.NON_RESERVED),
    ("week", "WEEK", KeywordCategory.NON_RESERVED),
    ("when", "WHEN", KeywordCategory.RESERVED),
    ("where", "WHERE", KeywordCategory.RESERVED),
    ("whitelist", "WHITELIST", KeywordCategory.NON_RESERVED),
    ("with", "WITH", KeywordCategory.RESERVED),
    ("work", "WORK", KeywordCategory.NON_RESERVED),
    ("workload", "WORKLOAD", KeywordCategory.NON_RESERVED),
    ("write", "WRITE", KeywordCategory.NON_RESERVED),
    ("xor", "XOR", KeywordCategory.NON_RESERVED),
    ("year", "YEAR", KeywordCategory.NON_RESERVED),
]


# ============================================================
# Lookup dictionaries (built at module load)
# ============================================================
RESERVED_KEYWORDS = set()
NON_RESERVED_KEYWORDS = set()
ALL_KEYWORDS = {}  # name_lower -> (token_name, category)

for _name, _token, _category in KEYWORD_ENTRIES:
    ALL_KEYWORDS[_name] = (_token, _category)
    if _category == KeywordCategory.RESERVED:
        RESERVED_KEYWORDS.add(_name)
    else:
        NON_RESERVED_KEYWORDS.add(_name)


def is_keyword(name):
    """Check if name is a Doris keyword (case-insensitive)"""
    return name.lower() in ALL_KEYWORDS


def get_keyword_info(name):
    """Get keyword info: (token_name, category) or None"""
    return ALL_KEYWORDS.get(name.lower())


def get_keyword_category(name):
    """Get keyword category or None"""
    info = get_keyword_info(name)
    return info[1] if info else None


def is_reserved_keyword(name):
    """Check if name is a Doris reserved keyword (cannot be used as bare identifier)"""
    return name.lower() in RESERVED_KEYWORDS


def is_non_reserved_keyword(name):
    """Check if name is a Doris non-reserved keyword (can be used as identifier)"""
    return name.lower() in NON_RESERVED_KEYWORDS


def keyword_token_name(name):
    """Get the grammar token name for a keyword"""
    info = get_keyword_info(name)
    return info[0] if info else None


def get_keyword_count():
    """Return total keyword count"""
    return len(ALL_KEYWORDS)


def get_reserved_count():
    """Return reserved keyword count"""
    return len(RESERVED_KEYWORDS)


def get_non_reserved_count():
    """Return non-reserved keyword count"""
    return len(NON_RESERVED_KEYWORDS)


if __name__ == "__main__":
    print(f"Total Doris keywords: {get_keyword_count()}")
    print(f"Reserved: {get_reserved_count()}")
    print(f"Non-reserved: {get_non_reserved_count()}")
